/* ===== Music Player ===== */
const MUSIC = {
  currentIndex: 0, currentPlaylist: 0, audio: null, skipCount: 0, mode: 0,
  playlists: [
    { name: "📡 私人雷达",
      songs: [
        { id: 1451335147, title: "Birdcage", artist: "Novo Amor", cover: "https://p2.music.126.net/JCJRrGH_KjO2p43eK-tREg==/109951165092772805.jpg?param=200y200", lyric: "'Cause I'll be better in the morning  /  It went on and on and on without you  /  All the best, I made it through" },
        { id: 2605882837, title: "GMan", artist: "FEEEleven/周夏影/JYnostop", cover: "https://p2.music.126.net/RxIjqGELE6r-78jO2FUWeQ==/109951169763834013.jpg?param=200y200", lyric: "空气中仿佛在飘着rihanna的歌声  /  我成熟到开始模仿我叔叔穿polo  /  黄昏让这夕阳瞬间老得像锅巴" },
        { id: 3378909144, title: "辞职信", artist: "ChiliChill乐团", cover: "https://p2.music.126.net/x1_zJ4Hboalxh_56GeOYoA==/109951173180770409.jpg?param=200y200", lyric: "一句“欢迎下次再来”眼眶却微红  /  饮料 第三杯 还是 这一种  /  冷凝水在杯壁画出了迷宫" },
        { id: 2757879966, title: "青萼时", artist: "Grrreta", cover: "https://p2.music.126.net/Esa4Elw4DGcQF7LhxT9AwA==/109951172181573791.jpg?param=200y200", lyric: "" },
        { id: 3368794777, title: "乱春", artist: "送春归", cover: "https://p2.music.126.net/syKHJLRQ7KQ5HimrjoE68g==/109951173136648280.jpg?param=200y200", lyric: "夜里生长白天睡着黑色小狗在罚站  /  蝴蝶就忘记相思  /  要一百朵春天身死" },
        { id: 3384747492, title: "the cure", artist: "Olivia Rodrigo", cover: "https://p2.music.126.net/PwYDn5IlZs7DqxvZ3cmwSg==/109951173259207437.jpg?param=200y200", lyric: "I'm unraveled  /  And it's good for me, I'm sure  /  I'm unraveled" },
        { id: 1451335151, title: "If We're Being Honest", artist: "Novo Amor", cover: "https://p2.music.126.net/JCJRrGH_KjO2p43eK-tREg==/109951165092772805.jpg?param=200y200", lyric: "So call me back in August  /  You called me up in August  /  Bury me in orbit" },
        { id: 3382115200, title: "Hit the Wall", artist: "Gracie Abrams", cover: "https://p2.music.126.net/fvEkVlI8td_-0E5-T0s5hQ==/109951173222441764.jpg?param=200y200", lyric: "I barely deserve it if you do stay  /  Now you can watch me hit the wall  /  I wish you would anyway" },
        { id: 3363281756, title: "Goodbye Henry. (feat. Al Green)", artist: "RAYE/Al Green", cover: "https://p1.music.126.net/O4c1u1HhhsHiS42b4maw0w==/109951172943499828.jpg?param=200y200", lyric: "But I will sing it for you anyway  /  As I'm watching you drive away  /  This is a sad song" },
        { id: 3370152972, title: "绕路", artist: "黄丽玲", cover: "https://p1.music.126.net/t6XgNW2AQ-1FcCgAtL7rMw==/109951173048708369.jpg?param=200y200", lyric: "看归宿 变回地址 最后删除  /  不怕付出 冒充成幸福  /  终究降落 别处" }
      ]
    },
    { name: "🎵 我喜欢的歌",
      songs: [
{ id: 2712194305, title: "No Broke Boys", artist: "Disco Lines/Tinashe", cover: "?param=200y200", lyric: "No broke boys no new friends  /  No one really gets over me  /  Ain't no lie ain't no shade" },
        { id: 2601212283, title: "坏杀手", artist: "探长", cover: "?param=200y200", lyric: "你站在聚光灯的舞台  /  我不舍得清醒  /  你是天上的恒星" },
        { id: 2068215868, title: "赤と青", artist: "ROTH BART BARON", cover: "?param=200y200", lyric: "夜の世界が とても 雄弁ですから  /  色たちが 流れの中を 泳ぐように  /  固まった筆を 水で 解くように" },
        { id: 2122615322, title: "Forget it （feat. Mac Ova Seas）", artist: "SETI/mac ova seas", cover: "?param=200y200", lyric: "Say u never ever leave from beside me  /  两个⼈不停的提⾼防备  /  那感觉是莫名的真实" },
        { id: 410519050, title: "是我不够好", artist: "李毓芬", cover: "?param=200y200", lyric: "你在等的那个人投入是否也一样深  /  是我还不够好所以他不愿承认  /  是我还不够好所以他不愿承认" },
        { id: 22831636, title: "My jealousy (Original ver.)", artist: "DJMAX", cover: "?param=200y200", lyric: "(you and me,i can see, come on)  /  just tell me  /  Baby girl I know you went to me" },
        { id: 1964850580, title: "我本将心向明月", artist: "王朝1982/朱旭BooBoo", cover: "?param=200y200", lyric: "一举成名他名扬  /  不是一番寒彻骨，  /  十年窗下无人问，" },
        { id: 1809318575, title: "日久生情，与这波澜不惊", artist: "阿肆", cover: "?param=200y200", lyric: "只是不平凡  /  很少再有  /  曾��多愁善感" },
        { id: 2064857455, title: "孤单心事 (爱你是孤单的心事)", artist: "刘思思", cover: "?param=200y200", lyric: "有的时候我宁愿  /  你对我坏一点  /  比我幸福一点" },
        { id: 2725948142, title: "荒诞儿戏", artist: "在虚无中永存", cover: "?param=200y200", lyric: "" },
        { id: 1951069525, title: "精卫", artist: "30年前，50年后", cover: "?param=200y200", lyric: "是现在我所有期待  /  用什么去对待  /  臭读几篇书" },
        { id: 1412266089, title: "好想好想你", artist: "G.E.M.邓紫棋", cover: "?param=200y200", lyric: "工作  有没有太多烦恼  /  我好想好想好想你  /  真的好想好想好想你" },
        { id: 1973665667, title: "海屿你", artist: "马也_Crabbit", cover: "?param=200y200", lyric: "就像开败的花  /  我们之间的故事还不多  /  我却对你情有独钟" },
        { id: 167870, title: "如果当时", artist: "许嵩", cover: "?param=200y200", lyric: "还笑那曹操贪慕着小乔  /  视线要模糊了  /  又为什么 现在变得冷淡了" },
        { id: 32683748, title: "听", artist: "方大同", cover: "?param=200y200", lyric: "再不能言喻 并不明了  /  音乐突破了时间 空间  /  我屏着呼吸好几口" },
        { id: 1410633323, title: "到时说爱我", artist: "茜拉", cover: "?param=200y200", lyric: "他的昵称 已改称 一句陌生  /  就当转身 是暖身 未来缘分  /  回忆总夜里漂泊" },
        { id: 2013101293, title: "About Me", artist: "AViVA", cover: "?param=200y200", lyric: "You don't know a thing  /  About me  /  Of me" },
        { id: 18374823, title: "Everybody", artist: "Ingrid Michaelson", cover: "?param=200y200", lyric: "in this world it's hard to get it right  /  Everybody, everybody wants to love  /  Everybody, everybody wants to love" },
        { id: 205342, title: "给我一个理由忘记", artist: "黄丽玲", cover: "?param=200y200", lyric: "深夜里的脚步声总是刺耳  /  只是哪怕周围再多人感觉还是一个人  /  只是哪怕周围再多人感觉还是一个人" },
        { id: 1950046157, title: "蝴蝶夫人", artist: "黄霄雲/王赫野", cover: "?param=200y200", lyric: "王赫野：  /  明白你的离开  /  OP/SP：好乐无荒" },
        { id: 2132833231, title: "Don't Leave (Sped Up)", artist: "Tom Frane/RJ Pasin", cover: "?param=200y200", lyric: "Don't leave, don't leave  /  Just leave, babe, babe, babe  /  Oh baby, baby" },
        { id: 2661735192, title: "病态的爱", artist: "Zkaaai/哈利白特", cover: "?param=200y200", lyric: "对不起我没管它  /  离别时说的话  /  没有资格再多说" },
        { id: 273114, title: "失眠", artist: "Suki刘舒妤", cover: "?param=200y200", lyric: "忍住怀念 却清醒过 一整夜  /  爱情像纠结的毛线  /  这个失眠夜 想不起你是谁" },
        { id: 2625474498, title: "inside you", artist: "ギギ・アンダルシア", cover: "?param=200y200", lyric: "繰り返しのscene瞳の裏貼りついたscreen  /  遠く消える テールライト 照らして  /  Tell me who is inside 許されるなら" },
        { id: 2731496391, title: "英雄主义Pt.2", artist: "在虚无中永存/Youzee Music", cover: "?param=200y200", lyric: "小提琴演奏：RO Maestro/ German D.  /  大提琴演奏：Daniel G. (Venezuela)" },
        { id: 2024035483, title: "就让这大雨全都落下", artist: "郑润泽", cover: "?param=200y200", lyric: "省得还需要你忘记  /  最矫情的情绪  /  都结束吧 说心里话" },
        { id: 811721, title: "コンプリケイション -still struggle version-", artist: "ROOKiEZ is PUNK'D", cover: "?param=200y200", lyric: "苛立ち混じりの唾を吐く  /  強がってみてもマジ辛いぜ  /  重圧に押しつぶされそうで" },
        { id: 30706129, title: "GLASSY SKY", artist: "Donna Burke", cover: "?param=200y200", lyric: "the broken pieces of me  /  the mystery of it I recall  /  How many days have passed like this" },
        { id: 3312626447, title: "letter", artist: "冰心", cover: "?param=200y200", lyric: "" },
        { id: 2719333628, title: "1-800", artist: "bbno$/Ironmouse", cover: "?param=200y200", lyric: "One eight zero zero  /  1800, he’s so handcome, he’s my hero  /  She-she-she-she makin’ me real coy." },
        { id: 511678913, title: "Sucker for You", artist: "Matt Terry", cover: "?param=200y200", lyric: "I'm just too weak to stay cool  /  I don't mind  /  Oh oh oh oh, oh oh" },
        { id: 30854479, title: "Memory", artist: "中島美嘉/DAISHI DANCE", cover: "?param=200y200", lyric: "Watching every town go by  /  I'm forever with the memory  /  Sweet tears fill my eyes" },
        { id: 22800559, title: "Memory feat.Mika Nakashima", artist: "中島美嘉", cover: "?param=200y200", lyric: "Everything I feel comes alive  /  One photograph that I keep with me  /  Hand in hand, at sunrise" },
        { id: 2690846498, title: "来电瑶", artist: "法老/By2", cover: "?param=200y200", lyric: "说你是可爱又迷人的反派角色  /  我想拥有虫电宝 能力  /  武器是糖豆一直打到他缴械" },
        { id: 165339, title: "万有引力", artist: "汪苏泷", cover: "?param=200y200", lyric: "是两颗星星眯着眼睛  /  想些深奥的问题  /  终于等到响起了下课铃" },
        { id: 63574, title: "背叛", artist: "曹格", cover: "?param=200y200", lyric: "尽管我细心灌溉  /  紧紧相依的心如何 say goodbye  /  我 一直不愿再去猜" },
        { id: 405485737, title: "Try Everything", artist: "Shakira", cover: "?param=200y200", lyric: "Oh oh oh oh oooh  /  No I won't leave,I wanna try everything  /  Oh oh oh oh oooh" },
        { id: 22746816, title: "Mr. 'Broken Heart'", artist: "松下優也", cover: "?param=200y200", lyric: "I cannot sleep “tonight”  /  想い出のいたずら  /  不意に　君が見せた　哀しい笑顔" },
        { id: 2755710644, title: "左转灯 (1000 Times +1)", artist: "派伟俊/mac ova seas", cover: "?param=200y200", lyric: "i miss u thousand times  /  回忆 降落没讯号的地方  /  留下的谎话 就写成小说 好吗？" },
        { id: 2755254306, title: "你最近还好吗", artist: "书亦", cover: "?param=200y200", lyric: "假如你半夜想起他  /  是否还会想起他  /  已经到了晚期" },
        { id: 1902251868, title: "好不容易", artist: "告五人", cover: "?param=200y200", lyric: "成熟带来的孤寂  /  你的手慢热的体温  /  或许这就是注定" },
        { id: 27969778, title: "For You", artist: "AZU", cover: "?param=200y200", lyric: "どんな時も頑張ってた事  /  やり直す事できるから  /  答え達よ  ほら自信もって進めばいい" },
        { id: 1352544631, title: "宠坏 (可不可以你把我宠坏)", artist: "小潘潘（潘柚彤）/李俊佑", cover: "?param=200y200", lyric: "仙女下凡来这个时代  /  可不可以你把我宠坏  /  拜拜生气就说拜拜" },
        { id: 1325896149, title: "即兴", artist: "小咪", cover: "?param=200y200", lyric: "一触碰就放不下  /  你现在好吗  /  哪怕结果悲哀" },
        { id: 1359260531, title: "You Should Get Over Me", artist: "Jessica Wolff", cover: "?param=200y200", lyric: "I know this come to an end now  /  I don't want your company or anything  /  You should get over me" },
        { id: 1403215687, title: "想见你想见你想见你", artist: "八三夭", cover: "?param=200y200", lyric: "会不会 你也 和我��样 在等待一句 我愿意  /  想穿越 每个平行 在未来 和过去 紧紧相依  /  未来 先进科技 无法模拟 你拥抱暖意" },
        { id: 1956990495, title: "Start Again", artist: "Connor Price/Chloe Sagum", cover: "?param=200y200", lyric: "Remember all the things we said  /  Took this long to finally feel up to  /  ooh..." },
        { id: 2749896430, title: "打火机", artist: "陌九", cover: "?param=200y200", lyric: "可我不习惯没有带着你的打火机  /  吉隆坡的天气它是翻云又覆雨  /  电影票和收据还留在我口袋里" },
        { id: 2668764089, title: "去远方", artist: "付俊乐", cover: "?param=200y200", lyric: "我不配在你身旁，  /  可我只有命运揉碎的理想，  /  让我变成一匹野马去远方，" },
        { id: 2005213526, title: "心许百年", artist: "王天戈", cover: "?param=200y200", lyric: "我真的会惋惜  /  流转的时间刚好用来了解  /  你仿佛带着标记" },
        { id: 1417849873, title: "一程山路", artist: "毛不易", cover: "?param=200y200", lyric: "它不问 你不答  /  旅人匆匆地赶路啊  /  山谷的薄雾吻着烟霞" },
        { id: 2731857320, title: "你最近还好吗 (Remix)", artist: "LvSo7", cover: "?param=200y200", lyric: "别让自己呆在家  /  吃巧克力记得要擦嘴巴  /  假如你半夜想起他" },
        { id: 2680959706, title: "春雪", artist: "裘德", cover: "?param=200y200", lyric: "是你的眼睛  /  喜欢却偏偏不敢靠近  /  原唱 : 10cm" },
        { id: 287248, title: "第一天", artist: "孙燕姿", cover: "?param=200y200", lyric: "你的眼神里 好像也期待  /  不见到你不是很习惯  /  永远 那么 灿烂" },
        { id: 1958148461, title: "丑话 Ugly Truth (Acoustic)", artist: "WILLIM缪维霖/不是花火呀", cover: "?param=200y200", lyric: "不用再哭泣  /  他们 站上了高地  /  况且我天生胆大" },
        { id: 247821, title: "阳光下的星星", artist: "金海心", cover: "?param=200y200", lyric: "恍然你又在身旁  /  暖暖阳光懒懒爬进窗  /  笑容星一样明亮" },
        { id: 2054171538, title: "麦当劳道没有麦当劳", artist: "庄东茹（豆芽鱼）", cover: "?param=200y200", lyric: "奇怪的想法怎么突然间就喧闹  /  麦当劳道 怎么 没麦当劳  /  仿佛看到 路人在笑" },
        { id: 208948, title: "晨间新闻", artist: "蔡健雅", cover: "?param=200y200", lyric: "Oh 今天又关注谁  /  微风依赖着我的大门  /  但我决定不闻也不问" },
        { id: 1926623288, title: "小胡同", artist: "郑润泽", cover: "?param=200y200", lyric: "不用我问太多  /  可我还是痛  /  那些回忆猛然再浮现" },
        { id: 1496770948, title: "Come Around Me", artist: "Justin Bieber", cover: "?param=200y200", lyric: "Oh no next thing you're on top of me  /  Treat me like you miss me  /  Let's get it in expeditiously" },
        { id: 1897927044, title: "习惯失恋", artist: "容祖儿", cover: "?param=200y200", lyric: "难道我未够好 未懂得热吻  /  想不起 被爱是如何温暖  /  相恋一刻 只是我的侥幸" },
        { id: 29850683, title: "浪漫血液", artist: "林俊杰", cover: "?param=200y200", lyric: "用赤裸去热情  /  爱凝结成泪的轨迹  /  到变懂得 变熟悉" },
        { id: 546723089, title: "IF YOU -JP Ver.-", artist: "BIGBANG", cover: "?param=200y200", lyric: "忘れるとか簡単じゃないよ  /  同じ痛みお互いに  /  でもオレは何も出来ず" },
        { id: 18638060, title: "Boyfriend", artist: "Justin Bieber", cover: "?param=200y200", lyric: "I am 'ma a make you shine bright  /  Swaggie  /  like you're laying in the snow Burr" },
        { id: 2096427703, title: "察觉", artist: "TC", cover: "?param=200y200", lyric: "你刻意⾛进雪⾥我看不⻅  /  有没有 有没有  /  离得很近却像在不同世界" },
        { id: 1911281594, title: "どうして", artist: "高瀬統也/野田愛実", cover: "?param=200y200", lyric: "どうして 君のこと  /  がむしゃらに好きだった  /  好きすぎたから 愛せなかったんだ" },
        { id: 25648006, title: "麦恩莉", artist: "方大同", cover: "?param=200y200", lyric: "把眼泪收回  /  怕爱再卷来  /  叫我期待重新振作起来" },
        { id: 316108, title: "匿名的好友", artist: "杨丞琳", cover: "?param=200y200", lyric: "回忆里被爱  /  也许我们  /  回忆里被爱" },
        { id: 1439814454, title: "我的悲伤是水做的", artist: "ChiliChill乐团/洛天依Official", cover: "?param=200y200", lyric: "是水做的 是水做的  /  新买的鞋子沾上泥  /  在哪里呢 在哪里呢" },
        { id: 287063, title: "我怀念的", artist: "孙燕姿", cover: "?param=200y200", lyric: "我怀念的 是争吵以后  /  也记得那一首歌  /  自尊常常将人拖着" },
        { id: 442869203, title: "保留", artist: "郭顶", cover: "?param=200y200", lyric: "只想让沉默的能开解  /  好让我不至于 太潦倒  /  已经忘了 你的名字" },
        { id: 25657348, title: "幸福了 然后呢", artist: "黄丽玲", cover: "?param=200y200", lyric: "才能平衡  /  却碰不到你的灵魂  /  每天就好像背对背的列车" },
        { id: 25642125, title: "你不知道的事", artist: "王力宏", cover: "?param=200y200", lyric: "你不知道我为什么离开你  /  夜空洒满了星星 但几颗会落地  /  很靠近 还听见呼吸" },
        { id: 65528, title: "淘汰", artist: "陈奕迅", cover: "?param=200y200", lyric: "Production Coordination: Stanley Leung  /  你却用离开烫下句点  /  我们的回忆没有皱褶" },
        { id: 1361988914, title: "孤单心事", artist: "颜人中", cover: "?param=200y200", lyric: "原唱：蓝又时  /  雨下在我窗前  /  有的时候我宁愿" },
        { id: 421486605, title: "孤雏", artist: "AGA", cover: "?param=200y200", lyric: "暂时度过坎坷  /  若平伏你风波  /  我的伤心" },
        { id: 33418857, title: "LAST STARDUST", artist: "Aimer", cover: "?param=200y200", lyric: "Dust to Dust  /  歩き続けた  /  Earth to Earth" },
        { id: 479219481, title: "Butterflies", artist: "Nohidea", cover: "?param=200y200", lyric: "" },
        { id: 419375250, title: "月亮之矢", artist: "孤矢/虞娱", cover: "?param=200y200", lyric: "需要手术  /  可是生活总是充满着各种悲剧  /  我穿过黑暗的夜" },
        { id: 27965209, title: "那时雨", artist: "徐良", cover: "?param=200y200", lyric: "在下竟着了迷  吻了你  /  （你说你是雨 会跟着云 哪里去）  /  为何却断了情  伤了心" },
        { id: 1367609755, title: "无心斗艳", artist: "大布/苏泽龙", cover: "?param=200y200", lyric: "它笑我在众人眼中的妆点  /  还不是一直等  /  遮住了最后道光线" },
        { id: 409872504, title: "ninelie", artist: "Aimer/EGOIST", cover: "?param=200y200", lyric: "どこへ叫び唱えても  /  どれも同じ雨に濡れた夢ばかり 乾くだけの光(こう)  /  君を繋ぐ空の星が1つ音を立てても" },
        { id: 517566417, title: "Memories", artist: "TRA$H", cover: "?param=200y200", lyric: "" },
        { id: 1379918404, title: "time machine (feat. aren park)", artist: "mj apanay/aren park", cover: "?param=200y200", lyric: "Wait every night  /  Why do we only have one chance to try  /  Cause if a star falls" },
        { id: 2080177728, title: "NUNA3.0", artist: "郑润泽", cover: "?param=200y200", lyric: "风铃吹呀吹 打湿了我的心扉  /  有好多话 都想当面表白  /  抱歉 把你 时间 全都浪费" },
        { id: 26093064, title: "Sacred Play Secret Place", artist: "Matryoshka", cover: "?param=200y200", lyric: "Confess my sin, conceal them all  /  I know I'm wrong  /  I can't help this vague feeling" },
        { id: 2686272114, title: "风铃", artist: "蒋孜怡", cover: "?param=200y200", lyric: "I'm falling in you  /  我还是不敢明说  /  共振的频率定格" },
        { id: 543798652, title: "少一点天分", artist: "孙盛希", cover: "?param=200y200", lyric: "错过了一个对的人 谁晓得  /  我们折腾了多少上天的缘分  /  我们都在爱情里少一点天分" },
        { id: 32358691, title: "Brave Shine", artist: "Aimer", cover: "?param=200y200", lyric: "Your brave shine  /  祈りは時を超えて  /  かざした刃の先に" },
        { id: 1946610374, title: "赛勒斯的爱", artist: "张敬轩", cover: "?param=200y200", lyric: "我愿能以后 捉紧你的手  /  偏偏当失去  /  让美梦数位里重温" },
        { id: 2166085823, title: "Called My Phone", artist: "❀", cover: "?param=200y200", lyric: "Dark clouds, you gon' see me storm  /  But trust me, you're gon' hold that  /  Know it's hurtin' you to see me gone" },
        { id: 108810, title: "不死之身", artist: "林俊杰", cover: "?param=200y200", lyric: "和北风狂妄的咆哮  /  任何事物 任何一切  /  不论你以为你是谁" },
        { id: 2005492223, title: "命运", artist: "家家", cover: "?param=200y200", lyric: "如果不是遇见你我不可能相信  /  爱可以相知相许相依为命  /  能不能脱下面具还可以很狠心" },
        { id: 2137732229, title: "云和雨", artist: "WiFi歪歪", cover: "?param=200y200", lyric: "天公不作美  /  雷雨交加翻来覆去  /  留下我一个人伤悲" },
        { id: 1363553440, title: "出现又离开 (Live)", artist: "梁博", cover: "?param=200y200", lyric: "各自生活的自在  /  谁也没有想过再想回来  /  当周围又安静起来" },
        { id: 108134, title: "学不会", artist: "林俊杰", cover: "?param=200y200", lyric: "总是学不会  /  我相信爱能证明一切  /  才发现爱不代表一切" },
        { id: 2686502900, title: "おしんこ", artist: "田中ユウスケ/agehasprings", cover: "?param=200y200", lyric: "" },
        { id: 2695458941, title: "Montagem Nada Tropica", artist: "Eternxlkz", cover: "?param=200y200", lyric: "De la fuma mala fuma  /  Puedo dar el control contigo papi  /  Porque no me aguanto drama de nada" },
        { id: 420401511, title: "和你", artist: "余佳运", cover: "?param=200y200", lyric: "许多回忆 藏在心底  /  那些事情 全因为你  /  我想和你 赏最美的风景" },
        { id: 1436117704, title: "不说 (原来是不说)", artist: "周公", cover: "?param=200y200", lyric: "什么距离  /  你都不关心  /  总有持无恐" },
        { id: 1382838382, title: "飛行艇", artist: "King Gnu", cover: "?param=200y200", lyric: "過ちを恐れないで  /  この時代に飛び乗って  /  果ての無いパーティーを　続けようか" },
        { id: 1969158110, title: "アディオス", artist: "DAZBEE", cover: "?param=200y200", lyric: "僕ら分かり合いたいが分からない  /  僕は分かり合えないなら逃げたい  /  僕は分かり合えないなら逃げたい" },
        { id: 28317262, title: "Complication", artist: "ROOKiEZ is PUNK'D", cover: "?param=200y200", lyric: "やっとの思（おも）い買（か）った　i-Pod  /  2010年9月2日までの期間生産限定盤/デュラララ!!盤/DVD付/デビュー作  /  心配（しんぱい）そうな目（め）で見（み）てるマイメン" },
        { id: 2726658017, title: "寂寞寂寞不好", artist: "刘大拿", cover: "?param=200y200", lyric: "baby I love you so  /  期待某天可以 晒恩爱  /  期待某天可以 晒恩爱" },
        { id: 26846129, title: "Rock Your Body", artist: "Black Eyed Peas", cover: "?param=200y200", lyric: "Rock ya body come on come on  /  All of my super fly ladies  /  Rock ya body" },
        { id: 1420706073, title: "离开我的依赖", artist: "王艳薇", cover: "?param=200y200", lyric: "才发现承诺是谎话  /  我来不及道声不安  /  看着你的模样" },
        { id: 2698002545, title: "DIA DELÍCIA", artist: "Nakama/ΣP", cover: "?param=200y200", lyric: "Mina linda, safadinha  /  E eu arregaço esse popô  /  Vai que é se- vai que é se-" },
        { id: 1306000879, title: "Grand Blue", artist: "湘南乃風", cover: "?param=200y200", lyric: "心 晴れ晴れ  /  青い空 飛び込め  /  お前のこと知りたいんだ もっと" },
        { id: 2720075876, title: "裸でどつきあい feat. May'n", artist: "SEAMO/May'n", cover: "?param=200y200", lyric: "深まる夜　本音も丸見え　もっともっとdeepに潜ろうぜ  /  try it now...  /  まずは脱いでくれ 裸のお付き合い　生き様と生き様のどつきあい" },
        { id: 39324743, title: "Renaissance", artist: "Steve James/Clairity", cover: "?param=200y200", lyric: "Heart torn, leaving blood stains  /  And I could never scrub them off  /  A renaissance, a renaissance" },
        { id: 1365475026, title: "Crazy Kids", artist: "Kesha", cover: "?param=200y200", lyric: "We are the crazy people  /  It's such a nuisance  /  And we are we are we are" },
        { id: 1498523311, title: "伯虎说 (feat.唐伯虎Annie)", artist: "伯爵Johnny/唐伯虎Annie", cover: "?param=200y200", lyric: "又摘桃花卖酒钱  /  酩酊寄此身  /  明月万年无前身" },
        { id: 2673175226, title: "零距离的思念", artist: "TINY7", cover: "?param=200y200", lyric: "除非让时间终结whole world  /  让盲目的爱变习惯延续浪漫  /  相遇是解药 却没治好那份恐慌" },
        { id: 537787665, title: "室内系的TrackMaker(YUNOMI)（翻自 nicamoq）", artist: "Hanser", cover: "?param=200y200", lyric: "松松领带 现在就是Chance  /  高峰期的街上 堆满车子  /  坐落在那地极的 Fashion Center" },
        { id: 25794008, title: "黑暗骑士", artist: "林俊杰/五月天", cover: "?param=200y200", lyric: "都关上双耳和双眼  /  Yeah Yeah  /  有没有一句誓言" },
        { id: 209936, title: "倒带", artist: "蔡依林", cover: "?param=200y200", lyric: "看到记忆慢下来  /  却一直都进不来  /  宁愿没出息 求我别离开" },
        { id: 431259256, title: "カタオモイ", artist: "Aimer", cover: "?param=200y200", lyric: "君だけ 分かってよ 分かってよ  /  山も谷も全部フルコースで  /  素晴らしい特別もいらない" },
        { id: 233888, title: "爱情讯息", artist: "郭静", cover: "?param=200y200", lyric: "写些什么秘密  /  心情也会下起大雨不会太美丽啊  /  需要勇气来面对决心" },
        { id: 229394, title: "最初的梦想", artist: "范玮琪", cover: "?param=200y200", lyric: "多渴望���得的人  /  最初的梦想绝对会到达  /  又怎会懂得要多努力" },
        { id: 25906124, title: "不要说话", artist: "陈奕迅", cover: "?param=200y200", lyric: "爱一个人是不是应该有默契  /  我以为你懂得每当我看着你  /  灯光再亮 也抱住你" },
        { id: 2709756720, title: "情结 (Live版)", artist: "张碧晨/徐子未", cover: "?param=200y200", lyric: "它让我迷失在荒野  /  Program : 郎梓朔@维伴音乐  /  你出现 又幻灭 是错觉" },
        { id: 1859515946, title: "Cure For Me", artist: "AURORA", cover: "?param=200y200", lyric: "No, we don't belong together  /  Unless they hurt, so you blamed it all  /  Heart I got" },
        { id: 354601, title: "你的微笑", artist: "F.I.R.", cover: "?param=200y200", lyric: "拥抱着地球闪耀  /  太多的幸福报到  /  我的微笑你明白就很好" },
        { id: 2671812705, title: "反乌托邦", artist: "乌托邦P", cover: "?param=200y200", lyric: "列车上坐错站的乘客  /  把愿望敲碎成粉末  /  在这个世界难免会迷茫" },
        { id: 1459675420, title: "极昼青春", artist: "冯沁苑(买辣椒也用券)", cover: "?param=200y200", lyric: "别回头 你能抓住的 只有此刻  /  冲撞着 爱的恨的怀念的 心动才不寂寞  /  醒过来全时空都在笑" },
        { id: 165361, title: "不分手的恋爱", artist: "汪苏泷", cover: "?param=200y200", lyric: "谁还记得那年我拉着你说  /  这场不分手的恋爱 我想结局注定失败  /  多少的时光" },
        { id: 1902115782, title: "Children In The Dark", artist: "AViVA", cover: "?param=200y200", lyric: "That you were looking for  /  Thought I could trust you  /  Get enough" },
        { id: 491294478, title: "Let Me Know", artist: "习谱予/文颖秋", cover: "?param=200y200", lyric: "要多久才不会保留  /  你的味道 陌生太早  /  So Let me know" },
        { id: 1937051360, title: "热铁皮房顶的夏天", artist: "王赫野", cover: "?param=200y200", lyric: "那个小铁匠 存钱买希望  /  混沌的梦弹琴的青年贩卖着来日  /  如果如果如果泰戈尔没写诗集" },
        { id: 38679524, title: "蠢货", artist: "喻言", cover: "?param=200y200", lyric: "听见吗 不要就 开门别再放狗  /  我说了NO 就是NO 别再对我放电  /  我的世界就算你要走进也没有意义" },
        { id: 1335942780, title: "九万字", artist: "黄诗扶", cover: "?param=200y200", lyric: "以讥诮这庸尘  /  最先动情的人  /  有谁不是 死而寻生" },
        { id: 2656126620, title: "后来我们的爱", artist: "苏星婕", cover: "?param=200y200", lyric: "我却无力再爱一遍  /  后来我们的爱从誓言变成谎言  /  后来我们的爱慢慢被收回搁浅" },
        { id: 1960749853, title: "听说我喜欢你", artist: "老番茄/Bo Peep", cover: "?param=200y200", lyric: "多想问我们能不能不只是做朋友  /  勾勒ta模样  /  嘿 我最近发现一个女孩" },
        { id: 2046795480, title: "见面就告白吧", artist: "庄东茹（豆芽鱼）", cover: "?param=200y200", lyric: "靠近点吧 在你耳边说出想法  /  想你感应到 打出直球必须趁早  /  如果不是 那天 阳光刚刚好" },
        { id: 1294899297, title: "I Love You So", artist: "The Walters", cover: "?param=200y200", lyric: "But I love you so  /  I love you so  /  'Cause you were cruel and I'm a fool" },
        { id: 1905096353, title: "манго нектар", artist: "Corn Wave", cover: "?param=200y200", lyric: "Попробуй только лишь глоток  /  О том что сказано забудь  /  Божественный нектар природы" },
        { id: 2048362753, title: "Perfect Version Of Me", artist: "Vicky宣宣", cover: "?param=200y200", lyric: "Oh, my heart is turning vacant  /  I try to change my mind  /  But in the next morning" },
        { id: 2692390754, title: "第57次取消发送", artist: "菲菲公主（陆绮菲）", cover: "?param=200y200", lyric: "念旧是上瘾感受  /  你现在在哪里  /  删掉的短信确定不想打扰" },
        { id: 1391891631, title: "嗜好", artist: "颜人中", cover: "?param=200y200", lyric: "我以为 能戒掉 不让回忆 打扰  /  当世界荒凉如岛 只有你能做停靠  /  忘不掉 想念你的嗜好" },
        { id: 2015896805, title: "浆果", artist: "TINY7", cover: "?param=200y200", lyric: "I lost  /  look  /  Cause your love" },
        { id: 234014, title: "写不完的温柔", artist: "G.E.M.邓紫棋", cover: "?param=200y200", lyric: "一直 旋绕在心头  /  感觉变淡 就写不完 不能勉强  /  最痛的痛 竟然由我 一手放纵" },
        { id: 1406649619, title: "有些", artist: "颜人中", cover: "?param=200y200", lyric: "房间还是乱糟糟  /  却淋湿双眼  /  你占据我世��� 却不在 身边" },
        { id: 1908049566, title: "算了吧", artist: "Aioz/张天枢/刘思达", cover: "?param=200y200", lyric: "准备了那么久那么久 鲜艳的花  /  你我的约定 被隐藏在了风铃里  /  未完的计划过半" },
        { id: 28403111, title: "特别的人", artist: "方大同", cover: "?param=200y200", lyric: "录制：Lightroom Studio  /  生命中有万事的可能  /  爱一个人或许要慷慨" },
        { id: 1303464858, title: "于是", artist: "郑润泽", cover: "?param=200y200", lyric: "倔强的我最后过回了沉溺  /  松开的手再抓不紧  /  最后再求你求你别离去" },
        { id: 2083785152, title: "唯一", artist: "G.E.M.邓紫棋", cover: "?param=200y200", lyric: "���是不嫉妒 不张狂 不求⾃⼰  /  你真的懂唯一的定义  /  我真的爱你 句句不轻易" },
        { id: 2645500113, title: "跳楼机", artist: "LBI利比", cover: "?param=200y200", lyric: "才知道孤独很难忍受  /  我好像一束极光  /  劫后余生好难呼吸" },
        { id: 1396023850, title: "很需要", artist: "颜人中", cover: "?param=200y200", lyric: "要求 算不算 太高  /  很需要 依靠  /  爱 很需要" },
        { id: 2655850235, title: "拼图爱", artist: "蒋孜怡/岳燃", cover: "?param=200y200", lyric: "VE在我生气时总是可怜巴巴  /  蓝色的天  /  不想让你生气只想当个恋爱专家" },
        { id: 863481092, title: "叹云兮", artist: "鞠婧祎", cover: "?param=200y200", lyric: "当我们命运重叠  /  陪你将八荒走遍  /  陪你把我的所念 写成最后的药笺" },
        { id: 2064842045, title: "Hold on", artist: "RICHNOMADIC", cover: "?param=200y200", lyric: "请你放下防备  /  我不屑那些没有你的夜  /  总是埋怨生活太背" },
        { id: 1468115100, title: "不为谁而作的歌", artist: "林俊杰", cover: "?param=200y200", lyric: "和他们关心的 的地方  /  爱在背后往前推  /  原谅我这一首" },
        { id: 150432, title: "爱我还是他", artist: "陶喆", cover: "?param=200y200", lyric: "陷在这个漩涡只想挣脱它  /  你就开始要逃  /  这是不是命运对我的惩罚" },
        { id: 21253809, title: "Lucky Strike", artist: "Maroon 5", cover: "?param=200y200", lyric: "My lucky strike  /  Oh oh oh my lucky strike  /  Your body rocking, keep me up all night" },
        { id: 2641978429, title: "劝学", artist: "银河系长", cover: "?param=200y200", lyric: "让他开口唱  /  她笑他是个假 rapper  /  但女同学对他说" },
        { id: 28613217, title: "눈, 코, 입", artist: "TAEYANG", cover: "?param=200y200", lyric: "혹시 우연이라도  /  타들어가버린  /  나는 괜찮아" },
        { id: 1295009639, title: "Again", artist: "王极", cover: "?param=200y200", lyric: "我怕你哭红了眼睛哭的快要瞎  /  我怕你又走丢了我的手别放下  /  是不是又剪短了你的头发" },
        { id: 501133611, title: "Look What You Made Me Do", artist: "Taylor Swift", cover: "?param=200y200", lyric: "Look what you just made me do  /  The role you made me play  /  They once belonged to me" },
        { id: 29747526, title: "Who Says", artist: "Selena Gomez", cover: "?param=200y200", lyric: "Who says you're not perfect?  /  That never gets to see the light.  /  Keep you beneath the stars." },
        { id: 1886345442, title: "Keep Your Head Up Princess", artist: "Anson Seabra", cover: "?param=200y200", lyric: "Yeah, keep your head up  /  And she got older, and it all changed  /  And now she's grown up, works at a bar" },
        { id: 500412390, title: "Contact", artist: "Lulleaux/Giang Pham", cover: "?param=200y200", lyric: "It's a physical chemical interaction  /  We are just two of a kind  /  It's a chain reaction" },
        { id: 484365611, title: "Parties", artist: "Jake Miller", cover: "?param=200y200", lyric: "But I think she's moved on already  /  I don't go to parties anymore  /  'Cause I can't see her face right now" },
        { id: 3986017, title: "Viva La Vida", artist: "Coldplay", cover: "?param=200y200", lyric: "Revolutionaries Wait  /  Roman Cavalry choirs are singing  /  Blew down the doors to let me in." },
        { id: 2163210456, title: "两 难", artist: "加木", cover: "?param=200y200", lyric: "慢慢错付一切了断  /  漆黑的夜由火点亮  /  期不期待会慢慢慢来" },
        { id: 2074440239, title: "主 动", artist: "加木", cover: "?param=200y200", lyric: "抱忽远忽近的安全感  /  终于全部拥有她的爱  /  心跳太快" },
        { id: 1410815174, title: "death bed (coffee for your head)", artist: "Powfu/beabadoobee", cover: "?param=200y200", lyric: "I'll make a cup of coffee for your head  /  [Verse 2: Powfu]  /  I'll get you up and going out of bed" },
        { id: 169243, title: "认真的雪", artist: "薛之谦", cover: "?param=200y200", lyric: "可还是听见了  /  可还是听见了  /  爱得那么认真" },
        { id: 36307815, title: "Lose Control", artist: "Hedley", cover: "?param=200y200", lyric: "Baby never give a ****  /  They're gonna love the sound  /  Can I get a hell yeah?" },
        { id: 25729074, title: "因你而在", artist: "林俊杰", cover: "?param=200y200", lyric: "我为你心跳 我为你祈祷  /  只许你无理取闹  /  我要和你拥抱" },
        { id: 28308080, title: "Me and My Broken Heart", artist: "Push Baby", cover: "?param=200y200", lyric: "Hold me so I'm not falling apart  /  Why do we call this love  /  Tell me to stay oh why-y" },
        { id: 1356248072, title: "YELLOW", artist: "神山羊", cover: "?param=200y200", lyric: "「私馬鹿な子なのどこにも行かないで」  /  狡猾な術なら試したんだ  /  but 後悔 low-lifeならば敢えて" },
        { id: 520458166, title: "Sunflower Feelings", artist: "Kuzu Mellow/korou.", cover: "?param=200y200", lyric: "I would rather be alone than have you  /  I only fell for you baby  /  It's just the two of us my dear" },
        { id: 108242, title: "她说", artist: "林俊杰", cover: "?param=200y200", lyric: "只是美丽的独秀太折磨  /  只要能在夜里 翻来覆去的时候有寄托  /  等不到天黑 烟火不会太完美" },
        { id: 385973, title: "恋爱ing", artist: "五月天", cover: "?param=200y200", lyric: "心情就像是坐上一台喷射机  /  L-O-V-E L-O-V-E  /  恋爱ing Happy-ing" },
        { id: 167827, title: "素颜", artist: "许嵩/何曼婷", cover: "?param=200y200", lyric: "一个人窝在摇椅里乘凉  /  一个人窝在摇椅里乘凉  /  听说你还在搞什么原创" },
        { id: 167873, title: "多余的解释", artist: "许嵩", cover: "?param=200y200", lyric: "她只是我的妹妹 我在担心你是否误会  /  她只是我的妹妹 我在担心你是否误会  /  怕眼光不行 所以叫着紧跟潮流的妹妹和我一起" },
        { id: 1815389717, title: "Celebrity", artist: "IU", cover: "?param=200y200", lyric: "떨군 고개 위  /  오래된 사랑시  /  넌 모르지" },
        { id: 5238992, title: "偏爱", artist: "张芸京", cover: "?param=200y200", lyric: "相信自己的直觉  /  我说过 我不闪躲  /  如果我错了也承担" },
        { id: 1833391733, title: "人体解冻", artist: "姜涵John Senco", cover: "?param=200y200", lyric: "我不想再给自己找借口  /  夏天，雨夜，看风雪  /  不停开着列车" },
        { id: 424155395, title: "Jumpshot", artist: "Dawin", cover: "?param=200y200", lyric: "Boom shakala boom shakala ooh  /  Clock  /  Score" },
        { id: 2120125578, title: "底牌", artist: "Max李玄/邹沛沛", cover: "?param=200y200", lyric: "哪怕我们  /  Max：  /  do re mi fa" },
        { id: 482636088, title: "Barricades", artist: "澤野弘之/R!N/Gemie/mpi/Yosh", cover: "?param=200y200", lyric: "Lost everything  /  Can now be tamed to go  /  We've got to learn to" },
        { id: 1374051000, title: "木偶人", artist: "薛之谦", cover: "?param=200y200", lyric: "看裹小脚的人  为诗人的恶习在隐忍  /  谁定的烂台本  可当代都在跟  气氛已麻木不仁  /  你何苦再做一个痴情人表忠贞" },
        { id: 2657015668, title: "Take Me to the Beach", artist: "Imagine Dragons/Ado", cover: "?param=200y200", lyric: "Ah-ah-ah, you take the snow  /  I owe, oh-oh-oh  /  People-pleasin' planet" },
        { id: 1960619633, title: "Coco Elva Tia", artist: "马思唯/JZlee", cover: "?param=200y200", lyric: "你想去巴黎我现在开始学法文  /  我是个说唱歌手但具备R&B vibe  /  我们是俩张唱片把他交给 DJ" },
        { id: 438801672, title: "让我留在你身边", artist: "陈奕迅", cover: "?param=200y200", lyric: "这世界太大  /  在你身边是谁  /  没有人回答" },
        { id: 354500, title: "千年之恋", artist: "F.I.R.", cover: "?param=200y200", lyric: "竹林的灯火  /  有一种神秘  /  七色的国度" },
        { id: 1374061028, title: "慢半拍", artist: "薛之谦", cover: "?param=200y200", lyric: "和人潮一起  别标新立异  /  这年头谁挑剔 反正一片狼藉  /  献给时代审美统一" },
        { id: 165367, title: "三国杀", artist: "汪苏泷", cover: "?param=200y200", lyric: "千军万马我无懈  /  狼火烽烟我敷衍  /  羽扇纶巾笑谈间" },
        { id: 37653063, title: "Please Don't Go", artist: "Joel Adams", cover: "?param=200y200", lyric: "Most nights I hardly sleep  /  Praying to the lord  /  Now please don't go" },
        { id: 66842, title: "十年", artist: "陈奕迅", cover: "?param=200y200", lyric: "我们是朋友  /  总有一个人要先走  /  只是那种温柔" },
        { id: 174963, title: "客官不可以", artist: "徐良/小凌", cover: "?param=200y200", lyric: "你靠的越来越近  /  小姐你是谁家的城堡  /  小心我真的生气" },
        { id: 440411424, title: "缘分一道桥", artist: "王力宏/谭维维", cover: "?param=200y200", lyric: "万里长征人未还  /  乱世孤魂无人访  /  远方胡笳催断肠" },
        { id: 32192436, title: "绅士", artist: "薛之谦", cover: "?param=200y200", lyric: "我能给你个拥抱  /  我忍不住从背后抱了一下  /  只是简单的试探啊" },
        { id: 176053, title: "洋葱", artist: "杨宗纬", cover: "?param=200y200", lyric: "一层地剥开我的心  /  偷偷的看着你  /  你会讶异" },
        { id: 1357953768, title: "だから僕は音楽を辞めた", artist: "ヨルシカ", cover: "?param=200y200", lyric: "今更なんだから  /  ねぇ、将来何してるだろうね  /  正しいかどうか知りたいのだって防衛本能だ" },
        { id: 29750962, title: "シルエット", artist: "KANA-BOON", cover: "?param=200y200", lyric: "わかってるって  /  何もないよ笑えるさ  /  流れる時と记忆" },
        { id: 4940920, title: "Butter-Fly", artist: "和田光司", cover: "?param=200y200", lyric: "WOW WOW WOW WOW WOW ～  /  ウカレタ蝶になって  /  忘れた方がマシさ" },
        { id: 1369903412, title: "海の幽霊", artist: "米津玄師", cover: "?param=200y200", lyric: "なにから話せばいいのか わからなくなるかな  /  星が降る夜にあなたにあえた  /  あなたがどこかで笑う 声が聞こえる" },
        { id: 1442320451, title: "小丑女", artist: "杨和苏KeyNG", cover: "?param=200y200", lyric: "她说的没错却剥夺了你所有体验  /  曾经你天真地以为这世界很自由  /  让我们报复" },
        { id: 440241201, title: "追梦的蚂蚁", artist: "JAEFOREAL/蜡笔大Boom", cover: "?param=200y200", lyric: "用尽全力要不然你的人生哪里来的意义  /  这世界多么巧妙  /  如果你曾经来过的话" },
        { id: 1998281031, title: "Nonsense (Sped Up Version)", artist: "Sabrina Carpenter", cover: "?param=200y200", lyric: "Yeah  /  [Intro]  /  Oh, it feels so good" },
        { id: 108406, title: "加油！", artist: "林俊杰/MC HotDog 热狗", cover: "?param=200y200", lyric: "曾经流过的泪  /  说好不见不散  /  什么是生命中的美好" },
        { id: 1981056341, title: "I Don’t Think That I Like Her", artist: "Charlie Puth", cover: "?param=200y200", lyric: "Never all the differences, oh, yeah  /  So I made just one the exception  /  I don't think that I like her anymore" },
        { id: 1951925907, title: "时间更改", artist: "庄东茹（豆芽鱼）", cover: "?param=200y200", lyric: "习惯  躲在深夜的天台  /  所以也羡慕  那些等待  /  该怎么戒掉我对你的依赖" },
        { id: 2008987398, title: "Baby you", artist: "有華", cover: "?param=200y200", lyric: "気づいてよ　ねえ　気づいてよ  /  ねえ今日は最低な気分  /  あの子と歩いてるのをみたの" },
        { id: 2036894489, title: "Cupid - Twin Ver. (FIFTY FIFTY) (Sped Up Version)", artist: "FIFTY FIFTY", cover: "?param=200y200", lyric: "La, la, la, la-la-la  /  But still, I want it more, more, more  /  I gave a second chance to Cupid" },
        { id: 2018432856, title: "循迹", artist: "王子健", cover: "?param=200y200", lyric: "你背过身 任由狂风轻易地吹灭我  /  恨不得要一整个透彻  /  像我们的纠葛" },
        { id: 1961056433, title: "肯定", artist: "RE-D/是二哈ya/Masta", cover: "?param=200y200", lyric: "只留存你的记忆 永远不清理  /  两个人的故事你我决定  /  如此肯定" },
        { id: 1381723556, title: "Call your name <Gv>", artist: "澤野弘之/R!N/Gemie", cover: "?param=200y200", lyric: "Calling out your name  /  I don't have the power  /  I'm crying" },
        { id: 255574, title: "恶作剧", artist: "林依晨", cover: "?param=200y200", lyric: "我想我已慢慢喜欢你  /  奇迹会发生也不一定  /  我找不到很好的原因" },
        { id: 308299, title: "喜帖街", artist: "谢安琪", cover: "?param=200y200", lyric: "裱起婚纱照那道墙  /  面对这 坟起的荒土 你注定学会潇洒  /  就似这一区 曾经称得上 美满甲天下" },
        { id: 25657526, title: "Catch My Breath", artist: "Kelly Clarkson", cover: "?param=200y200", lyric: "letting it go,  /  I'll spend the rest of my time  /  Catch my breath," },
        { id: 1990743306, title: "I Really Want to Stay at Your House", artist: "Samuel Kim/Lorien", cover: "?param=200y200", lyric: "I don't wanna know  /  So, get away  /  Let's start at the rainbow" },
        { id: 1954437911, title: "新時代 (ウタ from ONE PIECE FILM RED)", artist: "Ado", cover: "?param=200y200", lyric: "ミュージック  /  夢は見ないわ キミが話した  /  変えてしまえば" },
        { id: 1877070976, title: "クリームソーダとシャンデリア", artist: "Edo_Ame江户糖/草食考拉", cover: "?param=200y200", lyric: "知りたいだけよ本当  /  クリームソーダとシャンデリア  /  もうちょっと寝ておこう" },
        { id: 2026224214, title: "雪 Distance", artist: "Capper/罗言", cover: "?param=200y200", lyric: "看不见你皎白的谎言  /  你说我自以为是  /  再靠近我一点" },
        { id: 1974443814, title: "我记得", artist: "赵雷", cover: "?param=200y200", lyric: "快来抱抱 快来抱抱我  /  可你怎记得我  /  她和我讲了很多关于你成长的故事 在星空另一端 思念从未停止 如同墓碑上的名字" },
        { id: 472045959, title: "The Cure", artist: "Lady Gaga", cover: "?param=200y200", lyric: "So baby tell me yes  /  I'm gonna heal you anyway  /  So baby tell me yes" },
        { id: 1383691441, title: "tired", artist: "vietra", cover: "?param=200y200", lyric: "Cry, I cry, as time passes by  /  I’m still down here  /  Tired, I’m tired, I’m feeling so tired" },
        { id: 1397324193, title: "Thinkin Bout You", artist: "Jonasu/Jantine", cover: "?param=200y200", lyric: "Falling down deep  /  Thinking bout you  /  Falling down deep" },
        { id: 1970794796, title: "心做（Breakbeat Mix）", artist: "xH2", cover: "?param=200y200", lyric: "君にどれだけ近づいても  /  叫んで 藻掻（もが）いて 瞼（まぶた）を腫らしても  /  僕の心臓は一つだけ" },
        { id: 557579433, title: "DAYBREAK FRONTLINE", artist: "めありー/Orangestar", cover: "?param=200y200", lyric: "13秒先もわかんなくたって  /  もう戻れないぜ  /  追い越してやるんだ" },
        { id: 2014336709, title: "我不曾忘记", artist: "花玲/张安琪/沐霏", cover: "?param=200y200", lyric: "约好啦 等我们都长大 再次遇见 要比现在更美  /  绿草和砂砾没有嘴巴  /  都说长大后会忘记童话" },
        { id: 1950112498, title: "ダンスホール", artist: "Mrs. GREEN APPLE", cover: "?param=200y200", lyric: "この世界はダンスホール  /  それに甘えすぎてる  /  足元にあるもの" },
        { id: 2013251291, title: "Night Dancer（慵懒女声）", artist: "酒酒井Anri", cover: "?param=200y200", lyric: "浮つく心にコーヒーを  /  また止まった落とす針を  /  まだ止まった刻む針も" },
        { id: 1409311773, title: "夜に駆ける", artist: "YOASOBI", cover: "?param=200y200", lyric: "「さよなら」だけだった  /  二人だけの空が広がる夜に  /  日が沈み出した空と君の姿" },
        { id: 1859652717, title: "Moon Halo", artist: "茶理理/TetraCalyx/Hanser/HOYO-MiX", cover: "?param=200y200", lyric: "What else should I engrave on my mind  /  A shoulder for the past  /  But it used to fly so high" },
        { id: 1870469768, title: "老人と海", artist: "ヨルシカ", cover: "?param=200y200", lyric: "風に乗って  /  遥か遠くへ まだ遠くへ  /  僕の想像力という重力の向こうへ" },
        { id: 1968598930, title: "Hurt", artist: "noli", cover: "?param=200y200", lyric: "쥐고 있는 내 손엔  /  Hurt nah nah  /  먼저 와서 보여줘" },
        { id: 2004339783, title: "答案", artist: "冠楚", cover: "?param=200y200", lyric: "发觉越想要解释 越乱  /  所以说 永远多长  /  然后紧接就会有 风雨" },
        { id: 865632948, title: "若把你", artist: "Kirsty刘瑾睿", cover: "?param=200y200", lyric: "你我矢志不渝 举��又齐眉  /  你便是那高山流水  /  绝弦的美" },
        { id: 1994477687, title: "短裙你太美", artist: "威廉TEN", cover: "?param=200y200", lyric: "我现在已病入膏肓  /  我应该拿你怎样  /  第一次呀变成这样的我" },
        { id: 2005574298, title: "梦里花", artist: "苏星婕", cover: "?param=200y200", lyric: "原唱：张韶涵  /  指引真实方向  /  守护神秘时光" },
        { id: 1873049720, title: "初恋", artist: "回春丹", cover: "?param=200y200", lyric: "默默地伫候亦从来没怨  /  影子心里现  /  今天初发现" },
        { id: 1999878178, title: "王力宏-改变自己0.8x", artist: "Sensit5", cover: "?param=200y200", lyric: "看镜子里的我  /  最近比较烦 最近情绪很down  /  要一直 努力努力 永不放弃" },
        { id: 1500152660, title: "たぶん", artist: "YOASOBI", cover: "?param=200y200", lyric: "仕方がないよきっと  /  悪いのは君だ  /  埃は積もっていくんだ" },
        { id: 1988564487, title: "会魔法的老人", artist: "法老/KKECHO", cover: "?param=200y200", lyric: "无法去甄别 这是错的 或者是对的  /  时间可以倒退用我生命来换  /  在一张张的字据" },
        { id: 512376195, title: "灰色と青", artist: "米津玄師/菅田将暉", cover: "?param=200y200", lyric: "ひしゃげて曲がったあの自転車で走り回った  /  君は今もあの頃みたいにいるのだろうか  /  忘れることはないんだ" },
        { id: 496869422, title: "打上花火", artist: "Daoko/米津玄師", cover: "?param=200y200", lyric: "寄り返す波が  /  手を伸ばせば触れた  /  何度でも 言葉にして君を呼ぶよ" },
        { id: 432509390, title: "LOSER", artist: "米津玄師", cover: "?param=200y200", lyric: "今となっちゃもうわからない  /  アイムアルーザー ずっと前から聞こえてた  /  もうどこにも行けやしないのに 夢見ておやすみ" },
        { id: 1453894412, title: "アイロニ", artist: "majiko", cover: "?param=200y200", lyric: "捨ててきたはずなのに  /  ドン底まで突き落としてよ  /  少し歩き疲れたんだ" },
        { id: 496370620, title: "断线", artist: "Shang/lil sophy", cover: "?param=200y200", lyric: "I'm feeling really bad right now and um  /  走心的话我都留在心里面  /  酒后的真心话全都不屑" },
        { id: 1807799505, title: "唯一", artist: "告五人", cover: "?param=200y200", lyric: "总是在关键时刻清楚洞悉  /  你真的希望你能厘清 闭上眼睛 用心看清  /  没人能比拟" },
        { id: 1856722728, title: "好きだから。", artist: "『ユイカ』", cover: "?param=200y200", lyric: "あきれるなぁ。  /  貴方が欲しくて、  /  貴方を考えながら" },
        { id: 1945796091, title: "ただ声一つ", artist: "ロクデナシ", cover: "?param=200y200", lyric: "今日だって 笑う笑う  /  泣かぬように  /  を集めている ただ" },
        { id: 461544126, title: "Don't Wanna Know", artist: "Maroon 5", cover: "?param=200y200", lyric: "I don't wanna know  /  and loving you so, so, so, so  /  Who's taking you home, home, home, home" },
        { id: 1484336476, title: "恋のうた", artist: "Yunomi/鬼頭明里", cover: "?param=200y200", lyric: "花火が消えたら  /  君のいる景色が濃いな  /  色褪せる木々" },
        { id: 1408713927, title: "失眠症 Insomnia (抒情版)", artist: "姚智鑫", cover: "?param=200y200", lyric: "SP：Outdustry Songs Limited  /  Feels like insomnia ah ah,  /  Maybe in time, you'll change your mind" },
        { id: 514761281, title: "白羊", artist: "徐秉龙/沈以诚", cover: "?param=200y200", lyric: "然后沉迷 你诗写一般的身体  /  却是下落不详  /  几千几万个你" },
        { id: 731297, title: "わがまま", artist: "遊女", cover: "?param=200y200", lyric: "お姫様でいたい  /  もう近づける  /  この手触れるには　遠すぎる" },
        { id: 1993092103, title: "6", artist: "起风等花落", cover: "?param=200y200", lyric: "爱让我为了你改变  /  多想在你身边  /  只为了你孤注一掷的勇敢" },
        { id: 1472480890, title: "群青", artist: "YOASOBI", cover: "?param=200y200", lyric: "自分で選んだこの道を  /  嗚呼いつもの様に  /  また慌ただしくもがいてる" },
        { id: 1500439504, title: "Take Me Hand", artist: "Cécile Corbel", cover: "?param=200y200", lyric: "Won't you let me go  /  In my dreams  /  That is shining on the fields" },
        { id: 1830448879, title: "年轮", artist: "不是花火呀", cover: "?param=200y200", lyric: "寒夜剩我一个人等清晨  /  春去秋来的茂盛  /  密密麻麻是我的自尊" },
        { id: 1480078061, title: "PAIN", artist: "DUSTCELL", cover: "?param=200y200", lyric: "災れたTシャツを脱ぎ捨て  /  頭を一掻きしたなら  /  大嫌いだったこの季節だ" },
        { id: 1880127698, title: "门的另一端", artist: "多多poi/宴宁", cover: "?param=200y200", lyric: "闻不到的饭香  /  直到云朵透出日落果的色彩  /  从来没有过" },
        { id: 31234244, title: "Blessing 世界版", artist: "茶理理/V.A.", cover: "?param=200y200", lyric: "Blessings for your everyday  /  W acapella stylu zaśpiewasz tak  /  Comme ca, comme ca, yeah" },
        { id: 1983534049, title: "如果突然想起我", artist: "喵☆酱/花玲/爆裂菊是也", cover: "?param=200y200", lyric: "难道说，最近心情是雷雨交加？  /  再重复三次暗示你要常来看看我  /  最近新学了什么" },
        { id: 1373140736, title: "Throwaway", artist: "SG Lewis/Clairo", cover: "?param=200y200", lyric: "Baby, show me all that I can do  /  And I'll be here waiting, yeah  /  Some**mes I know what's right for me" },
        { id: 1435828582, title: "Empty Love", artist: "Lulleaux/Kid Princess", cover: "?param=200y200", lyric: "Don't want no empty love  /  Oh-oh  /  Oh-oh" },
        { id: 1338149101, title: "Believer", artist: "Imagine Dragons/Lil Wayne", cover: "?param=200y200", lyric: "Singing from heartache from the pain  /  Let's get mathematic, I'm up in this  /  The master of my sea, oh-ooh" },
        { id: 38592976, title: "Dream It Possible", artist: "Delacey", cover: "?param=200y200", lyric: "And if it takes, takes a thousand lives  /  And we’ll dream it possible it possible  /  Jumping out of my skin, pull the chord" },
        { id: 2308499, title: "My Heart Will Go On (Love Theme from 'Titanic')", artist: "Céline Dion", cover: "?param=200y200", lyric: "You have come to show you go on  /  And last for a lifetime  /  I feel you" },
        { id: 16607998, title: "The Show", artist: "Lenka", cover: "?param=200y200", lyric: "I know, I've got to let it go  /  It's bringing me down  /  The sun is hot in the sky" },
        { id: 509728841, title: "Moshi Moshi", artist: "Poppy", cover: "?param=200y200", lyric: "Hi, hello  /  Living like the typical girls  /  I like you and you like me" },
        { id: 1307463441, title: "PLASTIC", artist: "sakehands/LO/marty valentine", cover: "?param=200y200", lyric: "See I'd buy everything but I probably-  /  Spend some things all on me? (What?)  /  (Where'd you get that?)" },
        { id: 1404596131, title: "See You Again", artist: "See You Again", cover: "?param=200y200", lyric: "Good things we've been through  /  Now I see you in a better place  /  First you both go out your way" },
        { id: 521416693, title: "So Far Away", artist: "Martin Garrix/David Guetta/Jamie Scott/Romy Dya", cover: "?param=200y200", lyric: "Too many fights, and we cried  /  Stop saying you love me  /  So far away" },
        { id: 440208643, title: "Psycho, Pt. 2", artist: "Russ", cover: "?param=200y200", lyric: "Got me living on a tightrope  /  She got me going down  /  She got me going psycho" },
        { id: 530986903, title: "Lucky One", artist: "mich", cover: "?param=200y200", lyric: "Without you I'm a train wreck  /  Your perfect hands fit right into mine  /  I have underlined," },
        { id: 28878559, title: "Edge Of My Life", artist: "Manafest", cover: "?param=200y200", lyric: "Cause I, I know I'll get by  /  It's more than I can bear  /  When I'm standing with the weight" },
        { id: 28256115, title: "I Do", artist: "911", cover: "?param=200y200", lyric: "smiles by the thousands  /  everything was perfect  /  I'll be by your side till the day I die" },
        { id: 1491585, title: "Traveling Light", artist: "Joel Hanson/Sara Groves", cover: "?param=200y200", lyric: "Was a weight I carried with me everyday  /  Now I'm traveling light  /  Down by the riverside" },
        { id: 1351219081, title: "Old Town Road", artist: "Lil Nas X", cover: "?param=200y200", lyric: "I got the horses in the back  /  You can whip your Porsche  /  You can't tell me nothin'" },
        { id: 1915796767, title: "Numb Little Bug", artist: "Em Beihold", cover: "?param=200y200", lyric: "With a name I can't pronounce  /  And the world, it feels too big  /  Am I past repair?" },
        { id: 1355147933, title: "bad guy", artist: "Billie Eilish", cover: "?param=200y200", lyric: "I'm that bad type  /  My mommy likes to sing along with me  /  Make your mama sad type" },
        { id: 36199034, title: "Sorry", artist: "Justin Bieber", cover: "?param=200y200", lyric: "Yeah, is it too late now to say sorry?  /  Yeah,is it too late now to say sorry?  /  Is it too late to say sorry now?" },
        { id: 415904452, title: "Treat You Better", artist: "Shawn Mendes", cover: "?param=200y200", lyric: "I know I can treat you better  /  And you can tell me if I'm off  /  But I see it on your face" },
        { id: 427142481, title: "Clsr (Aash Mehta Flip)", artist: "The Chainsmokers/Aash Mehta/Halsey", cover: "?param=200y200", lyric: "Stay and play that Blink-182 song  /  Now I'm looking pretty in a hotel bar  /  That I know you can't afford" },
        { id: 1873321491, title: "Wake (Live)", artist: "Hillsong Young & Free", cover: "?param=200y200", lyric: "The streets will glow forever bright  /  Your glory's breaking through the night  /  Tune our hearts into Your beat" },
        { id: 1382592787, title: "天空下着小雨", artist: "hanji/Young 7", cover: "?param=200y200", lyric: "除了你以外的东西 都不放在心上  /  返程的高铁上又哼了一首melody  /  每日每夜没有你的每天" },
        { id: 489302317, title: "雀跃", artist: "任然/小来", cover: "?param=200y200", lyric: "bass：朱鸽  /  沉寂已久的心情掀起了雀跃  /  沉寂已久的心情掀起了雀跃" },
        { id: 1426238141, title: "Why You Look Sad?", artist: "舵Diverseddie", cover: "?param=200y200", lyric: "Meme我都不用就能把你逗笑  /  I want to know 我想了解  /  Yeah 耶" },
        { id: 1835685452, title: "STARZ", artist: "Lyf Fx", cover: "?param=200y200", lyric: "Leave too fast, never slow down  /  And thank you for teaching me  /  Look at bottle I see right through" },
        { id: 406407033, title: "Scars To Your Beautiful", artist: "Alessia Cara", cover: "?param=200y200", lyric: "The world could change its heart  /  You know, covergirls eat nothing  /  She just wants to be beautiful" },
        { id: 493705597, title: "Mama", artist: "Jonas Blue/William Singe", cover: "?param=200y200", lyric: "Where should we run to  /  Where should we run to  /  We coming home tonight" },
        { id: 1803410723, title: "gone", artist: "convolk", cover: "?param=200y200", lyric: "It's gone  /  ​Gone  /  Marry on a dirt floor, gone" },
        { id: 1217823, title: "Be What You Wanna Be", artist: "Darin", cover: "?param=200y200", lyric: "you can be just the one you wanna be  /  you can be just the one you wanna be  /  cause nothing last for ever" },
        { id: 1889492218, title: "Life Goes On", artist: "Dj Perreo Mix", cover: "?param=200y200", lyric: "You double faced entendre  /  Babe, you're too controlin'?  /  And life goes on and on" },
        { id: 28411642, title: "Shadow of the Sun", artist: "Max Elto", cover: "?param=200y200", lyric: "Changing colors makes you waste away,  /  They say that life is always easier,  /  building mountains in disguise," },
        { id: 1907712555, title: "Lost & Found", artist: "Embody/Claire Ridgely", cover: "?param=200y200", lyric: "I roll my window down  /  I roll my window down  /  Your home disappears in the rearview" },
        { id: 405167971, title: "Timber", artist: "MattyBRaps", cover: "?param=200y200", lyric: "Another found  /  Look what I found wait let me see  /  I rest long just for the begin" },
        { id: 1304347114, title: "Watch Me Work", artist: "Tinashe", cover: "?param=200y200", lyric: "Someone I can call the one  /  Wanna feel it wanna I feel it  /  Uh oh body‘s low before you know" },
        { id: 500410102, title: "Run Free (feat. IVIE)", artist: "Deep Chills/IVIE", cover: "?param=200y200", lyric: "You're still heaven to me  /  On you  /  That you say my name" },
        { id: 864100958, title: "小鹿乱撞", artist: "永彬Ryan.B/狄迪（D-DAY）", cover: "?param=200y200", lyric: "这感觉就像在  /  I’m feeling good  /  啊 你的套路被我看透" },
        { id: 518894487, title: "Loosing Interest (Original Mix)", artist: "timmies/Shiloh Dynasty", cover: "?param=200y200", lyric: "Losing interest  /  Just let me  /  When you move on..." },
        { id: 28718313, title: "The Way I Still Love You", artist: "Reynard Silva", cover: "?param=200y200", lyric: "You can tell me the truth  /  Memories running through my head  /  Still it's no use" },
        { id: 463159617, title: "All Time Low (Cash Cash Remix)", artist: "Cash Cash/Jon Bellion", cover: "?param=200y200", lyric: "Lie, lie, lie I tried to hide  /  I, I've been trying to fix my pride  /  But now you know it" },
        { id: 1428495562, title: "Drowning Love", artist: "Sanmmy Margan", cover: "?param=200y200", lyric: "" },
        { id: 1386495856, title: "May I see U again-I love you 3000 times（翻自 MT1990）", artist: "MappleZS", cover: "?param=200y200", lyric: "" },
        { id: 1951102443, title: "I Ain't Worried", artist: "OneRepublic", cover: "?param=200y200", lyric: "I ain't worried 'bout it  /  I should be scared, honey, maybe so  /  Keeping dreams alive, 1999, heroes" },
        { id: 18161816, title: "Let Her Go", artist: "Passenger", cover: "?param=200y200", lyric: "Staring at the ceiling in the dark  /  Maybe one day you'll understand why  /  Staring at the bottom of your glass" },
        { id: 1876179147, title: "别怕变老", artist: "王以太/艾热 AIR", cover: "?param=200y200", lyric: "但你依然swag（有型）好像还站在舞台上面  /  想要我都给你 从来不说假话  /  守卫着你直到掉光我的头发" },
        { id: 1962364527, title: "别怕变老 (LIVE版)", artist: "王以太/艾热 AIR", cover: "?param=200y200", lyric: "就算被苦痛肆虐  /  老天派我来  /  悲欢离合" },
        { id: 1971659843, title: "我要的·2022", artist: "旺仔小乔/Subs 张毅成", cover: "?param=200y200", lyric: "不想再失态  /  oh no no 节奏放慢的生活  /  人生很短的" },
        { id: 1309833126, title: "粉色苏打", artist: "安全着陆/木秦", cover: "?param=200y200", lyric: "你唇膏的taste  印象根深蒂固  /  五彩斑斓世界你是唯一  /  hook：木秦" },
        { id: 1824025894, title: "慢热", artist: "满舒克", cover: "?param=200y200", lyric: "识破了我心里所有慌张  /  星星的深邃距离  /  月光让思念安静" },
        { id: 1815105886, title: "狐狸的童话", artist: "Santa_SA/马也_Crabbit", cover: "?param=200y200", lyric: "我不甘心与你只做普通朋友  /  心里的秘密要用童话去做缓冲  /  我还是以前一样喜欢城堡和骑士" },
        { id: 1888622459, title: "天公不作美", artist: "Stake", cover: "?param=200y200", lyric: "天上的小⻦  /  每天都⻜来⻜去  /  其实不在意" },
        { id: 557667045, title: "足够", artist: "周星星", cover: "?param=200y200", lyric: "不小心脑袋里 勾勒出你的轮廓  /  电台里的音乐太过 刺耳朵  /  天长地久 这种话不需要说" },
        { id: 1401226842, title: "恋爱告急", artist: "鞠婧祎", cover: "?param=200y200", lyric: "指缝中青涩萌芽  /  脸红后也倾盆而下  /  恋爱是逆反心理" },
        { id: 1474157407, title: "有人喜欢 (萝莉女rapper高甜版)", artist: "Cindy", cover: "?param=200y200", lyric: "当你素面朝天会有人喜欢  /  在你快要飘的时候  /  你身上每一寸的肌肤" },
        { id: 475479888, title: "在你的身边", artist: "盛哲", cover: "?param=200y200", lyric: "我想在你的身边  /  像秋天落叶温柔整个世界  /  恨就恨了我从没想过" },
        { id: 1439608841, title: "有人喜欢", artist: "殷文艺", cover: "?param=200y200", lyric: "喜欢的花都会在这里盛开  /  你爱吃汉堡包  /  没有关的窗户一定尽量开大一点" },
        { id: 1962305293, title: "再见莫妮卡", artist: "苏星婕/王忻辰", cover: "?param=200y200", lyric: "【此版本为正版授权】  /  只能心里默念  /  话都说了一万遍" },
        { id: 1958654138, title: "见爱响铃", artist: "是二智呀", cover: "?param=200y200", lyric: "趣日无多 相濡以沫  /  哎呀哎呀  /  大胆撕破我假装的防备 诶" },
        { id: 1959667345, title: "给你一瓶魔法药水", artist: "告五人", cover: "?param=200y200", lyric: "我期待的是  今天的晚餐 你想吃哪里  /  我们一起去太空旅行  /  不管多远多近多累都没关系" },
        { id: 1961991016, title: "至夏", artist: "NINEONE#乃万", cover: "?param=200y200", lyric: "想对你说Hi  /  跟上你的脚印  /  没什么不该" },
        { id: 1832506754, title: "航行", artist: "蒋小呢", cover: "?param=200y200", lyric: "坚守着你我最后的约定  /  你到底在哪一个星球  /  为了你我的约定愿意穿越整个宇宙" },
        { id: 1436575829, title: "鱼", artist: "冯政FireDrippin/李铭辰/FAKE持续输出/巴鲁斯", cover: "?param=200y200", lyric: "追逐所谓的彩虹可我还离不开牢笼  /  感受着耳边的呼啸  /  你像只精灵自由穿梭在我这片海中" },
        { id: 1418580938, title: "四重罪孽", artist: "纳豆nado/倪莫问/颜素susu/大哥L-", cover: "?param=200y200", lyric: "可我也把世界破坏  /  这样一切就会终结  /  我创造了那些色彩" },
        { id: 427542143, title: "Cutting Shapes", artist: "Don Diablo", cover: "?param=200y200", lyric: "Dancin's what makes me whole  /  Dancin', dancin', dancin'  /  Dancin', dancin', dancin'" },
        { id: 1932464291, title: "好烦噢 (寒风吹进我的家)", artist: "穆傲寒", cover: "?param=200y200", lyric: "我的床才能让我提高效率  /  不要在我耳朵旁边啰嗦  /  我喊了声妈妈" },
        { id: 863104636, title: "勇敢爱", artist: "張咩/孙紫涵", cover: "?param=200y200", lyric: "不知不觉我爱上了 ta  /  一起欢笑一起疯  /  你的与众不同" },
        { id: 19292984, title: "Love Story", artist: "Taylor Swift", cover: "?param=200y200", lyric: "And I said  /  So close your eyes  /  Begging you please don't go" },
        { id: 1934251776, title: "小城夏天", artist: "LBI利比", cover: "?param=200y200", lyric: "闷热的季节 因你而梦幻  /  橘黄色的日落 吞没在海平线  /  从等你下课 到手写的从前" },
        { id: 1949108901, title: "最美好的时光 (Live)", artist: "陳嫺靜/范例三/山姆Someshit/桃子A1J/AndyShow安迪秀/KEYNO", cover: "?param=200y200", lyric: "美好是把你缩进我的万花筒  /  你是鲜花让我来当那牛粪  /  你不是女人是美丽的绿洲" },
        { id: 1922888354, title: "苦茶子", artist: "Starling8/DRODUMANA/FIVESTAR", cover: "?param=200y200", lyric: "在半坡我看到一丝残影  /  除非忘掉你的所有  /  Hook" },
        { id: 1923927650, title: "Bet On Me", artist: "Walk off the Earth/D Smoke", cover: "?param=200y200", lyric: "Gonna wanna get behind me like l'm 23  /  You can't get these odds in Vegas  /  Bending the rules like Inception" },
        { id: 441612583, title: "City Of Stars (From 'La La Land' Soundtrack)", artist: "Ryan Gosling/Emma Stone", cover: "?param=200y200", lyric: "A glance  /  Just one thing everybody wants  /  That now our dreams" },
        { id: 1938756186, title: "Bet On Me (Organic Version)", artist: "Walk off the Earth/D Smoke", cover: "?param=200y200", lyric: "Mama I made it look at look at me  /  Self-made with no pedigree  /  Gonna wanna get behind me like I'm 23" },
        { id: 1851652156, title: "忘不掉的你", artist: "h3R3", cover: "?param=200y200", lyric: "最熟悉的面孔  /  你的理由  /  多么怕 你放开的太过容易了" },
        { id: 29412405, title: "In The Shadow Of The Sun", artist: "Professor Green", cover: "?param=200y200", lyric: "After you let yourself come undone  /  As the sun creeps through the curtains  /  And it feels... feels amazing" },
        { id: 306877, title: "遗失的心跳", artist: "萧亚轩", cover: "?param=200y200", lyric: "我让日夜颠倒  /  心跳却感应不到  /  心痛着 你的爱 残酷的纪念" },
        { id: 1907766514, title: "11", artist: "队长/黄礼格", cover: "?param=200y200", lyric: "过了很久了么  /  过得好吗想说的话你能听到吗  /  Die for you" },
        { id: 108931, title: "美人鱼", artist: "林俊杰", cover: "?param=200y200", lyric: "现实里有了我对你的眷恋  /  所有蜚语流言 完全视而不见  /  你抬头就看见" },
        { id: 1901371647, title: "孤勇者", artist: "陈奕迅", cover: "?param=200y200", lyric: "爱你孤身走暗巷  /  谁说污泥满身的不算英雄  /  爱你破烂的衣裳" },
        { id: 441491828, title: "水星记", artist: "郭顶", cover: "?param=200y200", lyric: "最亲密的距离  /  也等着和你相遇  /  它依然真实地" },
        { id: 174956, title: "坏女孩", artist: "徐良/小凌", cover: "?param=200y200", lyric: "我喜欢坏坏的女友  /  你消失在无名大街  /  我喜欢坏坏的女友" },
        { id: 29774171, title: "新地球", artist: "林俊杰", cover: "?param=200y200", lyric: "纽约在海底的角落  /  灰色的土地很枯燥  /  新地球 他们这么叫" },
        { id: 1834076023, title: "等风吹", artist: "不是花火呀/小田音乐社", cover: "?param=200y200", lyric: "等风和云吻别  /  风一吹 你像颤抖蝴蝶  /  偏偏只剩下落叶" },
        { id: 208891, title: "Letting Go", artist: "蔡健雅", cover: "?param=200y200", lyric: "你是呼吸的空气  /  I’m letting go  /  或许就像他们说" },
        { id: 1846337727, title: "Maybe You Call Me / 法老-Call me maybe&百变酒精（$LeLe remix）", artist: "莱昂", cover: "?param=200y200", lyric: "Your stare was holding  /  But now you're in my way  /  Hot night" },
        { id: 1889702364, title: "小雨天气", artist: "yihuik苡慧/Kui Kui/十七草", cover: "?param=200y200", lyric: "脑海里都是你  /  这个创意从哪听来  /  月亮眨眨眼睛我把你放在手心" },
        { id: 1459935719, title: "我看过", artist: "周星星", cover: "?param=200y200", lyric: "我看过你说谎的方式  /  我看过你说好一辈子  /  我看过爱情自然变质" },
        { id: 1336205537, title: "Letting Go", artist: "陈老兮", cover: "?param=200y200", lyric: "因为爱你爱到我心痛  /  脱离不了的地心引力  /  翻唱：陈老兮" },
        { id: 1873679928, title: "想你知道", artist: "余奥成Ace/诺鸽鸽", cover: "?param=200y200", lyric: "或许是命运的安排 我看得出来  /  脸上的表情不需要再次说明  /  其实炙热的爱 不需要回声" },
        { id: 1371046568, title: "不喜欢下雨天", artist: "PIggy", cover: "?param=200y200", lyric: "我讨厌坏天气  /  你喜欢的  /  你讨厌被惦记" },
        { id: 1456991489, title: "想要你在身边", artist: "倪莫问/一条小团团OvO", cover: "?param=200y200", lyric: "万家灯火感觉  /  你在，我心里面  /  情诗再藏点" },
        { id: 1891685808, title: "sea蕊-独行侠+爱如潮水(TONY_Hardstyle Mashup Bootleg)", artist: "TONY", cover: "?param=200y200", lyric: "已变得模糊抽象  /  拖着疲惫不堪 的身体  /  sea蕊：" },
        { id: 533713714, title: "马步谣（Cover 双笙）", artist: "倪莫问", cover: "?param=200y200", lyric: "东头江湖八卦印成册子卖得正欢  /  晓来酩酊一场醉卧钟声禅  /  悠悠暗香悄然青梅盈袖扶摇云梦颠" },
        { id: 26902923, title: "My Cookie Can", artist: "卫兰", cover: "?param=200y200", lyric: "You give me security  /  手信要永远藏铁罐中  /  Hey you say love me till the end" },
        { id: 1909414208, title: "Normal No More", artist: "Strictlyviolin荀博/马克", cover: "?param=200y200", lyric: "企划 : 黄雨薇/欧阳慧琳  /  音频编辑 : Jaydos @ Ammobox Productions  /  原唱 : TYSM" },
        { id: 30431367, title: "走马", artist: "陈粒", cover: "?param=200y200", lyric: "空荡荡的自我  /  难过时你走了走了走了  /  路人穿街过河" },
        { id: 504652401, title: "我爱你 Luv Is Luv", artist: "贺仙人", cover: "?param=200y200", lyric: "oh baby I just can’t leave u now  /  前所未有的明朗  /  因为我爱你就像…" },
        { id: 1440570723, title: "Normal No More", artist: "TYSM", cover: "?param=200y200", lyric: "Don't lose any sleep at night, no  /  I don't wanna take drugs at the club  /  Don't wanna put out just for fun" },
        { id: 1445556953, title: "粉色星球", artist: "Youngior", cover: "?param=200y200", lyric: "My pink under moonlight  /  你是迷人的Lady  /  梦到你让我Crazy" },
        { id: 1903509018, title: "贴贴", artist: "胥睿/杨淳", cover: "?param=200y200", lyric: "吓得你不靠近我一点不着急  /  对着天空发射出爱的星星  /  其实我很心虚怕你激情褪去" },
        { id: 1432156509, title: "同样", artist: "Lambert凌杰/Lambert凌/杨胖雨/Pony Soore", cover: "?param=200y200", lyric: "为你神魂颠倒  /  看柔情似水 心神相随 直到鬓如霜  /  只因淑女窈窕" },
        { id: 1443838552, title: "他只是经过", artist: "h3R3/高旭", cover: "?param=200y200", lyric: "并没有停留  /  曾陪他逛过的每个路口  /  他现在又站在谁的对面" },
        { id: 1403318151, title: "把回忆拼好给你", artist: "王贰浪", cover: "?param=200y200", lyric: "时光匆匆却没有遗失过去  /  我们从清晨起玩一整天游戏  /  一直到天色渐晚看着落日无奈离开" },
        { id: 488249475, title: "哪里都是你", artist: "队长", cover: "?param=200y200", lyric: "而不是那遥远的未来  /  我忘掉你的所有 风里雨里一直大步往前走  /  没人能够控制住自己" },
        { id: 526464145, title: "喜欢", artist: "阿肆", cover: "?param=200y200", lyric: "一朝一夕 使我已固不可彻  /  扛住了 柴米油盐的麻烦  /  无时无刻" },
        { id: 1405650118, title: "天空下着小雨", artist: "YEYE/晚间星河", cover: "?param=200y200", lyric: "I promise 一直一直陪着你  /  我坐��副驾驶座 摇下了玻璃窗  /  love 小婕 come on" },
        { id: 1336856864, title: "形容", artist: "沈以诚", cover: "?param=200y200", lyric: "可能不经意看你一眼  /  心里石头都会落下  /  但偶尔也会闪出星星" },
        { id: 478303470, title: "心做し", artist: "双笙��陈元汐）", cover: "?param=200y200", lyric: "酷いよ酷いよ  /  全て投げ捨てられたら  /  僕の心臓は一つだけ" },
        { id: 1456890009, title: "罗生门（Follow）", artist: "梨冻紧/Wiz_H张子豪", cover: "?param=200y200", lyric: "可是下次我们还是争吵  /  你那里是怎么样的天气  /  每到晚上理智变得感性" },
        { id: 1326773330, title: "就这样和你在一起", artist: "蝴蝶效应(B.E.)", cover: "?param=200y200", lyric: "Verse1:  /  一起沦陷的雪月风花  /  心脏的转速 穿越你的身体几公里" },
        { id: 1899079967, title: "问心", artist: "就是南方凯", cover: "?param=200y200", lyric: "就当我丢了理性  /  结局不会太吃惊  /  当眼睛又模糊不清" },
        { id: 26305545, title: "期待爱", artist: "林俊杰/金莎", cover: "?param=200y200", lyric: "想要找回来  /  合：我要勇敢 大声说出来  /  真的好无奈" },
        { id: 108248, title: "只对你有感觉", artist: "林俊杰", cover: "?param=200y200", lyric: "我只对你有感觉  /  体贴却黏人 爱哭却温顺  /  但很矛盾 喜欢你的笨" },
        { id: 1867217766, title: "致你", artist: "yihuik苡慧", cover: "?param=200y200", lyric: "降落在你耳边低语  /  跌跌宕宕  /  恋恋不舍又念念不忘" },
        { id: 493735012, title: "无人之岛", artist: "任然", cover: "?param=200y200", lyric: "蓝色一望无际 我的你在哪里  /  从没有原因说明 一刹那的寂静  /  黑色的背后是黎明" },
        { id: 1835864375, title: "八小时差距", artist: "李嘉英", cover: "?param=200y200", lyric: "关于你黑的白的 假的真的都接受  /  而你的胸口  /  你相信吗 你说过的 承诺过的 付出的所有" },
        { id: 208902, title: "红色高跟鞋", artist: "蔡健雅", cover: "?param=200y200", lyric: "该怎么去形容你最贴切  /  却又像风捉摸不住  /  该怎么去形容你最贴切" },
        { id: 168039, title: "海芋恋", artist: "萧敬腾", cover: "?param=200y200", lyric: "春天的来临  /  你晶莹剔透的带着凉意  /  悄悄地释出暧昧的气息" },
        { id: 1869943939, title: "篝火旁（再启程）", artist: "吕大叶/旺仔小乔/马子林/我也想试试兔头", cover: "?param=200y200", lyric: "致敬或拙劣模仿 听到  /  历经过无数次重击却依然抬起头  /  Hold my hand" },
        { id: 1392752940, title: "娅咪（feat 尔玛娜依）", artist: "小爱/杨杰/阿拉梅", cover: "?param=200y200", lyric: "（纳吉纳鲁娅咪 噶个多芬娅咪）  /  （得吉扩玛娅咪 不斯斯莫多那哇）  /  他会听见的 或许是幻想" },
        { id: 1402508053, title: "再见前任", artist: "洛少爷/落樱风", cover: "?param=200y200", lyric: "嘿又是你 寒暄中带着 一丝犹豫  /  午后两点三十七  /  谈个恋爱费脑力" },
        { id: 1881736447, title: "山的那边还是山【旋律版】", artist: "叶轩", cover: "?param=200y200", lyric: "" },
        { id: 1467353016, title: "Why Would I Ever", artist: "JAWLAN", cover: "?param=200y200", lyric: "Why would i ever think of leaving you  /  I promise i'll be your girl  /  I been knowin you too long" },
        { id: 1831482748, title: "春娇与志明(抖音完整版)", artist: "珊爷", cover: "?param=200y200", lyric: "成长会进化吗 也信念自由  /  Jcool：  /  你话我唔识谂 用钱买无用饰品" },
        { id: 1398663411, title: "冬眠", artist: "司南", cover: "?param=200y200", lyric: "和风与暖阳倾斜  /  我如何把孤单融解  /  因为你才多了情结" },
        { id: 1830490788, title: "爱就一个字（女声版）", artist: "傲七爷（江偌绮）", cover: "?param=200y200", lyric: "爱就一个字  /  却无心看风景  /  两个人相互辉映" },
        { id: 1413338832, title: "心似烟火 (中日语版)", artist: "干净", cover: "?param=200y200", lyric: "(みんなほら)  /  那勇气却和时间偷偷溜走  /  信(しん)じれるもの" },
        { id: 1425896565, title: "幸福了 然后呢", artist: "吴炳文", cover: "?param=200y200", lyric: "却碰不到你的灵魂  /  只在深夜里会合  /  誓言 谎言" },
        { id: 1413623153, title: "Lutra", artist: "AD钙", cover: "?param=200y200", lyric: "暖 暖暖暖，  /  暖暖暖暖暖暖暖，  /  不是说好一人一半，" },
        { id: 1486264538, title: "心跳的证明", artist: "不是花火呀", cover: "?param=200y200", lyric: "这次换我 走向你  /  不过是背对而已  /  那些回忆 很清晰" },
        { id: 1331644760, title: "最好的我 治愈女声版", artist: "薯条猫", cover: "?param=200y200", lyric: "Guess You'll Never Know  /  我不会走 Cause I Love You So  /  在身后 陪 你微笑 或泪流" },
        { id: 38018486, title: "Collapsing World", artist: "Lightscape", cover: "?param=200y200", lyric: "" },
        { id: 1862710424, title: "Stay", artist: "The Kid LAROI/Justin Bieber", cover: "?param=200y200", lyric: "[Chorus: The Kid LAROI]  /  You're the reason I believe in love  /  [Verse 2: Justin Bieber]" },
        { id: 1417650764, title: "直觉（女版）", artist: "静香", cover: "?param=200y200", lyric: "欢迎来到只有你一个人的温柔世界  /  你为什么会那么美 你说什么都ok  /  你是谁家的小鬼 这么晚了还没睡" },
        { id: 1439363483, title: "小宇", artist: "张一", cover: "?param=200y200", lyric: "比方说当我遇见你  /  总有些惊奇的际遇  /  出现在我梦里" },
        { id: 1831820778, title: "不是因为寂寞才想你(DJ版)", artist: "精彩鹤七", cover: "?param=200y200", lyric: "不是因为寂寞才想你  /  让那指针慢慢走停在花开的时候  /  等到下一个春秋等到秋叶被红透" },
        { id: 1811662859, title: "西楼别序", artist: "尹昔眠/小田音乐社", cover: "?param=200y200", lyric: "夜色无言那醇酒只饮一口  /  只为你转身回眸  /  目送你背影依旧" },
        { id: 1410647903, title: "带我去找夜生活", artist: "告五人", cover: "?param=200y200", lyric: "时过境迁的伤悲  /  如果我还不停追  /  如果我就是绝对" },
        { id: 1368754688, title: "爱人错过", artist: "告五人", cover: "?param=200y200", lyric: "爱人就错过  /  相撞在街口  /  回头 转头 还是错" },
        { id: 1301884692, title: "烟雨行舟（原唱：伦桑）", artist: "司南", cover: "?param=200y200", lyric: "暮霭渐褪暗  /  一绵江风微拂素罗衫  /  缱绻怡然" },
        { id: 5255441, title: "说爱你", artist: "蔡依林", cover: "?param=200y200", lyric: "关于爱情  /  真爱 到现在 不敢期待  /  还窃喜 你 没发现我" },
        { id: 440353219, title: "九九八十一", artist: "特曼/裂天/张承煜（小魂）/满汉全席", cover: "?param=200y200", lyric: "【特曼】上路 鞏州遇虎熊  /  白毛小鼠偷烛花  /  腾霄又是孙悟空" },
        { id: 1877996649, title: "危险派对", artist: "王以太/刘至佳", cover: "?param=200y200", lyric: "Don’t hurt me  /  是我没把握你心跳的节奏  /  舞会开场" },
      ]
    }
  ],
  get songs() { return this.playlists[this.currentPlaylist].songs; },
init(){this.audio=document.getElementById("music-audio");if(!this.audio)return;
    const pb=document.getElementById("music-progress-bar");if(pb){pb.addEventListener("mousedown",()=>pb.dragging=true);pb.addEventListener("mouseup",()=>pb.dragging=false);pb.addEventListener("touchstart",()=>pb.dragging=true);pb.addEventListener("touchend",()=>pb.dragging=false)}
    this.audio.addEventListener("timeupdate",()=>this.updateProgress());this.audio.addEventListener("ended",()=>this.next());this.audio.addEventListener("error",()=>{if(this.audio.src)this.onError()});
    document.getElementById("btn-play")?.addEventListener("click",()=>this.togglePlay());
    document.getElementById("btn-prev")?.addEventListener("click",()=>this.prev());
    document.getElementById("btn-next")?.addEventListener("click",()=>this.next());
    this.renderTabs();this.renderSongList();
  },
  renderTabs(){const ct=document.getElementById("playlist-tabs");if(!ct)return;ct.innerHTML=this.playlists.map((pl,i)=>{const cls=i===this.currentPlaylist?" active":"";return '<span class="playlist-tab'+cls+'" onclick="MUSIC.switchPlaylist('+i+')">'+pl.name+'</span>'}).join("")},
  toggleMode(){const btn=document.getElementById("btn-mode");this.mode=(this.mode+1)%3;btn.textContent=["🔁","🔂","🔀"][this.mode];btn.title=["顺序播放","单曲循环","随机播放"][this.mode];btn.className="music-mode-btn";if(this.mode===1)btn.classList.add("repeat-one");if(this.mode===2)btn.classList.add("shuffle")},
  switchPlaylist(idx){this.currentPlaylist=idx;this.currentIndex=0;this.renderTabs();this.renderSongList();this.audio.pause();this.audio.src="";document.getElementById("music-cover-img").style.display="none";document.getElementById("music-title").textContent="选择一首歌吧";document.getElementById("music-artist").textContent="点击右侧歌单开始收听";document.getElementById("music-status").textContent="未播放";document.getElementById("btn-play").textContent="▶️";document.getElementById("music-progress").textContent="00:00 / 00:00";},
  renderSongList(){const ct=document.getElementById("music-songlist");if(!ct)return;ct.innerHTML=this.songs.map((s,i)=>{const cls=i===this.currentIndex?" active":"";const num=String(i+1).padStart(2,"0");return '<div class="music-song-item'+cls+'" onclick="MUSIC.play('+i+')"><span class="song-num">'+num+'</span><span>'+s.title+' — '+s.artist+'</span></div>'}).join("")},
  seekTo(pct){const a=this.audio;if(a&&a.duration)a.currentTime=(pct/100)*a.duration},
  
  play(index){this.currentIndex=index;this.skipCount=0;const s=this.songs[index],a=this.audio;a.src="https://music.163.com/song/media/outer/url?id="+s.id+".mp3";a.load();a.play().catch(()=>{});document.getElementById("music-title").textContent=s.title;document.getElementById("music-artist").textContent=s.artist;document.getElementById("music-cover-img").src=s.cover;document.getElementById("music-cover-img").style.display="block";document.getElementById("music-status").textContent="正在播放";document.getElementById("music-status").style.background="var(--accent-green)";this.renderSongList()},
  togglePlay(){const a=this.audio,b=document.getElementById("btn-play");if(!a.src){this.play(0);return}if(a.paused){a.play().catch(()=>{});b.textContent="⏸";document.getElementById("music-status").textContent="正在播放";document.getElementById("music-status").style.background="var(--accent-green)"}else{a.pause();b.textContent="▶️";document.getElementById("music-status").textContent="已暂停";document.getElementById("music-status").style.background="var(--text-light)"}},
  prev(){if(this.mode===2){this.next();return}this.play((this.currentIndex-1+this.songs.length)%this.songs.length)},
  next(){if(this.mode===1){this.play(this.currentIndex);return}if(this.mode===2){let r=Math.floor(Math.random()*this.songs.length);if(this.songs.length>1&&r===this.currentIndex)r=(r+1)%this.songs.length;this.play(r);return}this.play((this.currentIndex+1)%this.songs.length)},
  updateProgress(){const a=this.audio;if(!a||!a.duration)return;const pct=a.currentTime/a.duration*100;const pb=document.getElementById("music-progress-bar");if(pb&&!pb.dragging)pb.value=pct;const cur=Math.floor(a.currentTime/60)+":"+String(Math.floor(a.currentTime%60)).padStart(2,"0");const dur=Math.floor(a.duration/60)+":"+String(Math.floor(a.duration%60)).padStart(2,"0");document.getElementById("music-progress").textContent=cur+" / "+dur;if(!a.paused)document.getElementById("btn-play").textContent="⏸"},
  onError(){this.skipCount++;if(this.skipCount<=8){this.play((this.currentIndex+1)%this.songs.length);return}document.getElementById("music-status").textContent="播放失败";document.getElementById("music-status").style.background="var(--accent-pink)"}
};
/* ===== Daily Luck ===== */
const LUCK={init(){this.spin();document.querySelector('.luck-display')?.addEventListener('click',()=>this.spin())},spin(){const e=document.querySelector('.luck-display');if(!e)return;const tv=Math.floor(Math.random()*101),ring=e.querySelector('.luck-ring'),ve=e.querySelector('.luck-value'),te=e.querySelector('.luck-text');let c=0;const iv=setInterval(()=>{c+=Math.floor(Math.random()*5)+1;if(c>=tv){c=tv;clearInterval(iv);this.show(c,ring,ve,te)}ve.textContent=c},40)},show(v,ring,ve,te){let cl,em,msg;if(v<=20){cl='#FF8C8C';em='😢';msg='今天小心一点哦～'}else if(v<=50){cl='#FFD166';em='🙂';msg='平平淡淡才是真'}else if(v<=80){cl='#5CB85C';em='😊';msg='今天是好运日！'}else{cl='#FF6B35';em='🎉';msg='超级幸运日！！！'}ring.style.background='conic-gradient('+cl+' '+v+'%, #f0f0f0 '+v+'%)';ve.textContent=v+' '+em;te.textContent=msg;if(v>80)this.confetti()},confetti(){const ct=document.createElement('div');ct.className='confetti-container';const cs=['#FF6B35','#FFD166','#5CB85C','#004E98','#FF8C8C','#9B59B6'];for(let i=0;i<50;i++){const p=document.createElement('div');p.className='confetti-piece';p.style.left=Math.random()*100+'%';p.style.background=cs[Math.floor(Math.random()*cs.length)];p.style.borderRadius=Math.random()>.5?'50%':'2px';p.style.width=(Math.random()*8+4)+'px';p.style.height=(Math.random()*8+4)+'px';p.style.animationDelay=(Math.random()*2)+'s';p.style.animationDuration=(Math.random()*2+2)+'s';ct.appendChild(p)}document.body.appendChild(ct);setTimeout(()=>ct.remove(),4000)}};

/* ===== Daily Question ===== */
const QUESTION={questions:['今天让你微笑的一件事是什么？','你最近学到的一个新东西是什么？','如果可以穿越时空，你想去哪个时代？','你最喜欢的放松方式是什么？','今天吃的最好吃的食物是什么？','如果你有超能力，你想要什么能力？','最近单曲循环的一首歌是什么？','你做过最勇敢的事是什么？','如果可以去任何地方旅行，你想去哪？','你最近在看什么书/电影/剧？','今天有没有什么小确幸？','你小时候的梦想是什么？','如果明天是人生最后一天，你想做什么？','你最感激的人是谁？','什么颜色最能代表你今天的情绪？','你觉得自己最大的优点是什么？','给十年后的自己说一句话：','你最喜欢的一句台词或名言是什么？','如果养一只神奇的宠物，你养什么？','今天天气怎么样，你喜欢吗？'],init(){this.showQuestion();document.querySelector('.question-btn')?.addEventListener('click',()=>this.showQuestion())},showQuestion(){const e=document.querySelector('.question-text');if(!e)return;const t=new Date();const s=t.getFullYear()*10000+(t.getMonth()+1)*100+t.getDate();e.textContent='💡 '+this.questions[s%this.questions.length]}};

/* ===== Navigation ===== */
const NAV={init(){this.setupLinks();this.setupToggle();this.showPage('home')},setupLinks(){document.querySelectorAll('.nav-link').forEach(l=>l.addEventListener('click',e=>{e.preventDefault();const p=l.dataset.page;if(p)this.showPage(p)}))},setupToggle(){const t=document.querySelector('.nav-toggle'),ls=document.querySelector('.nav-links');if(t&&ls)t.addEventListener('click',()=>ls.classList.toggle('open'))},showPage(id){document.querySelectorAll('.nav-link').forEach(l=>l.classList.remove('active'));const al=document.querySelector('.nav-link[data-page="'+id+'"]');if(al)al.classList.add('active');document.querySelectorAll('.page-content').forEach(p=>p.classList.remove('active'));const tg=document.getElementById('page-'+id);if(tg){tg.classList.add('active');if(id==='games')GAMES.init()}document.querySelector('.nav-links')?.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}};

/* ===== Games ===== */
const GAMES={initialized:false,async init(){if(this.initialized)return;this.initialized=true;const sc=document.getElementById('snake-canvas'),tc=document.getElementById('tetris-canvas');if(sc&&typeof SNAKE!=='undefined')new SNAKE.Game(sc);if(tc&&typeof TETRIS!=='undefined')new TETRIS.Game(tc)}};

/* ===== Blog ===== */
const BLOG={articles:[{id:'hello-world',title:'Hello World! 我的小宇宙开张啦 🚀',date:'2026-06-24',tags:['生活','随笔'],tagClass:'tag-pink',excerpt:'终于搭建好了自己的小网站！这里会有技术分享、生活记录，还有一些好玩的互动小游戏。',content:'## 欢迎来到我的小宇宙！🎉\n\n终于搭建好了我的小站！\n\n### 这里会有什么？\n\n- 📝 **技术博客**\n- 🌱 **生活记录**\n- 🎃 **好玩的互动**\n- 📍 **音乐推荐**\n\n### 关于我\n\n一个热爱coding的开发者。'},{id:'my-first-game',title:'我用JS写了个贪吃蛇 🐍',date:'2026-06-24',tags:['前端','教程'],tagClass:'tag-blue',excerpt:'贪吃蛇是经典的入门项目，但做好玩也不简单。',content:'## 用Canvas写贪吃蛇\n\n核心思路很简单：用一个坐标数组表示蛇身，每次移动从头部插入新坐标，移除尾部。\n\n用了HSL渐变色让蛇看起来像彩虹，去🎮游戏页面就能玩啦～'}],init(){this.renderList()},renderList(){const c=document.getElementById('blog-list-container');if(!c)return;c.innerHTML=this.articles.map(a=>'<div class="blog-card" onclick="BLOG.open(\''+a.id+'\')"><h2>'+a.title+'</h2><div class="meta"><span>📮 '+a.date+'</span></div><p class="excerpt">'+a.excerpt+'</p><div class="tags">'+a.tags.map(t=>'<span class="tag '+a.tagClass+'">'+t+'</span>').join('')+'</div></div>').join('')},open(id){const a=this.articles.find(a=>a.id===id);if(!a)return;const c=document.getElementById('blog-list-container');const content=a.content.replace(/\\n/g,'<br>').replace(/## (.+)/g,'<h2>$1</h2>').replace(/### (.+)/g,'<h3>$1</h3>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>').replace(/^- (.+)/gm,'<li>$1</li>');c.innerHTML='<div class="article-detail"><button class="back-btn" onclick="BLOG.renderList()">← 返回</button><h1>'+a.title+'</h1><div class="meta">📮 '+a.date+' · 📂 '+a.tags.join(', ')+'</div><div class="content">'+content+'</div><button class="back-btn" onclick="BLOG.renderList()" style="margin-top:32px">← 返回</button></div>'}};

function initHomeArticles(){const l=document.querySelector('.article-list');if(!l)return;const as=BLOG.articles||[];l.innerHTML=as.slice(0,3).map(a=>'<div class="article-item" onclick="NAV.showPage(\'blog\')"><h3>'+a.title+'</h3><div class="meta"><span>📮 '+a.date+'</span><span class="tag '+a.tagClass+'">'+a.tags[0]+'</span></div></div>').join('')}

document.addEventListener('DOMContentLoaded',()=>{MUSIC.init();NAV.init();LUCK.init();QUESTION.init();BLOG.init();initHomeArticles()});